<div class="flash error">
    <h1>Action not found</h1>
    <p><strong>Error: </strong>Action not found <b><?= $action ?></b>. It is necessary to define a method in the controller class <b>
            <?= $Controller ?></b> called <b><?= $action ?></b> For this to work properly.</p>
</div>
<div class="flash valid">
    <h1>Solution</h1>
    <h4><strong> Create the method <em><?= $action ?></em> from below in class <b><?= $Controller ?></b> of the file : <br>
            <em class="file"><?= APP_PATH, 'controllers/', $controller_path, '_controller.php' ?></em></strong></h4>
    <pre>
<?php highlight_string("<?php
class {$Controller} extends AppController 
{
    public function {$action}() 
    {
    
    }
	
}") ?>
</pre>
</div>