<p> Prefix <b><?php if (isset($_SESSION['look'])) {
                    echo $_SESSION['look'];
                } else {
                    echo $_SESSION['user'];
                } ?>_</b> will be automaticaly added to database name and database user.</p>
<div class="col-4">
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>
    <form name="v_add_db" action="https://<?= $_SERVER['HTTP_HOST'] ?>/db/add" method="post">
        <label for="v_database">Database</label> <span style="color:red">*</span>
        <div class="input-group mb-3">
            <input type="text" name="v_database" class="form-control" placeholder="Database" required>
        </div>

        <!-- <p>maximum 16 characters length, including prefix</p> -->

        <label for="v_dbuser">Username</label> <span style="color:red">*</span>
        <div class="input-group mb-3">
            <input type="text" name="v_dbuser" class="form-control" placeholder="Username" required>
        </div>
        <label for="v_password">Password</label> <span style="color:red">*</span>&nbsp; / &nbsp; <a href="javascript:randomString();" class="generate"><?php print __('generate'); ?></a>
        <div class="input-group mb-3">
            <input type="text" name="v_password" class="form-control" placeholder="Password" required>
        </div>
        <label for="v_type">Type</label>
        <div class="input-group mb-3">
            <select name="v_type" class="form-control">
                <?php
                foreach ($db_types as $key => $value) { ?>
                    <option value="<?= $value ?>"><?= $value; ?></option>
                <?php } ?>
            </select>
        </div>
        <label for="v_host">Host</label>
        <div class="input-group mb-3">
            <select name="v_host" class="form-control">
                <?php
                foreach ($db_hosts as $key => $value) { ?>
                    <option value="<?= $value ?>"><?= $value; ?></option>
                <?php } ?>
            </select>
        </div>
        <label for="v_charset">Charset</label>
        <div class="input-group mb-3">
            <select class="form-control" name="v_charset">
                <option value=big5 <?php if ((!empty($v_charset)) && ($v_charset == 'big5')) echo 'selected'; ?>>
                    big5</option>
                <option value=dec8 <?php if ((!empty($v_charset)) && ($v_charset == 'dec8')) echo 'selected'; ?>>
                    dec8</option>
                <option value=cp850 <?php if ((!empty($v_charset)) && ($v_charset == 'cp850')) echo 'selected'; ?>>
                    cp850</option>
                <option value=hp8 <?php if ((!empty($v_charset)) && ($v_charset == 'hp8')) echo 'selected'; ?>>
                    hp8</option>
                <option value=koi8r <?php if ((!empty($v_charset)) && ($v_charset == 'koi8r')) echo 'selected'; ?>>
                    koi8r</option>
                <option value=latin1 <?php if ((!empty($v_charset)) && ($v_charset == 'latin1')) echo 'selected'; ?>>
                    latin1</option>
                <option value=latin2 <?php if ((!empty($v_charset)) && ($v_charset == 'latin2')) echo 'selected'; ?>>
                    latin2</option>
                <option value=swe7 <?php if ((!empty($v_charset)) && ($v_charset == 'swe7')) echo 'selected'; ?>>
                    swe7</option>
                <option value=ascii <?php if ((!empty($v_charset)) && ($v_charset == 'ascii')) echo 'selected'; ?>>
                    ascii</option>
                <option value=ujis <?php if ((!empty($v_charset)) && ($v_charset == 'ujis')) echo 'selected'; ?>>
                    ujis</option>
                <option value=sjis <?php if ((!empty($v_charset)) && ($v_charset == 'sjis')) echo 'selected'; ?>>
                    sjis</option>
                <option value=hebrew <?php if ((!empty($v_charset)) && ($v_charset == 'hebrew')) echo 'selected'; ?>>
                    hebrew</option>
                <option value=tis620 <?php if ((!empty($v_charset)) && ($v_charset == 'tis620')) echo 'selected'; ?>>
                    tis620</option>
                <option value=euckr <?php if ((!empty($v_charset)) && ($v_charset == 'euckr')) echo 'selected'; ?>>
                    euckr</option>
                <option value=koi8u <?php if ((!empty($v_charset)) && ($v_charset == 'koi8u')) echo 'selected'; ?>>
                    koi8u</option>
                <option value=gb2312 <?php if ((!empty($v_charset)) && ($v_charset == 'gb2312')) echo 'selected'; ?>>
                    gb2312</option>
                <option value=greek <?php if ((!empty($v_charset)) && ($v_charset == 'greek')) echo 'selected'; ?>>
                    greek</option>
                <option value=cp1250 <?php if ((!empty($v_charset)) && ($v_charset == 'cp1250')) echo 'selected'; ?>>
                    cp1250</option>
                <option value=gbk <?php if ((!empty($v_charset)) && ($v_charset == 'gbk')) echo 'selected'; ?>>
                    gbk</option>
                <option value=latin5 <?php if ((!empty($v_charset)) && ($v_charset == 'latin5')) echo 'selected'; ?>>
                    latin5</option>
                <option value=armscii8 <?php if ((!empty($v_charset)) && ($v_charset == 'armscii8')) echo 'selected'; ?>>
                    armscii8</option>
                <option value=utf8 <?php if ((!empty($v_charset)) && ($v_charset == 'utf8')) echo 'selected'; ?> <?php if (empty($v_charset)) echo 'selected'; ?>>utf8</option>
                <option value=utf8mb4 <?php if ((!empty($v_charset)) && ($v_charset == 'utf8mb4')) echo 'selected'; ?>>
                    utf8mb4</option>

                <option value=ucs2 <?php if ((!empty($v_charset)) && ($v_charset == 'ucs2')) echo 'selected'; ?>>
                    ucs2</option>
                <option value=cp866 <?php if ((!empty($v_charset)) && ($v_charset == 'cp866')) echo 'selected'; ?>>
                    cp866</option>
                <option value=keybcs2 <?php if ((!empty($v_charset)) && ($v_charset == 'keybcs2')) echo 'selected'; ?>>
                    keybcs2</option>
                <option value=macce <?php if ((!empty($v_charset)) && ($v_charset == 'macce')) echo 'selected'; ?>>
                    macce</option>
                <option value=macroman <?php if ((!empty($v_charset)) && ($v_charset == 'macroman')) echo 'selected'; ?>>
                    macroman</option>
                <option value=cp852 <?php if ((!empty($v_charset)) && ($v_charset == 'cp852')) echo 'selected'; ?>>
                    cp852</option>
                <option value=latin7 <?php if ((!empty($v_charset)) && ($v_charset == 'latin7')) echo 'selected'; ?>>
                    latin7</option>
                <option value=cp1251 <?php if ((!empty($v_charset)) && ($v_charset == 'cp1251')) echo 'selected'; ?>>
                    cp1251</option>
                <option value=cp1256 <?php if ((!empty($v_charset)) && ($v_charset == 'cp1256')) echo 'selected'; ?>>
                    cp1256</option>
                <option value=cp1257 <?php if ((!empty($v_charset)) && ($v_charset == 'cp1257')) echo 'selected'; ?>>
                    cp1257</option>
                <option value=binary <?php if ((!empty($v_charset)) && ($v_charset == 'binary')) echo 'selected'; ?>>
                    binary</option>
                <option value=geostd8 <?php if ((!empty($v_charset)) && ($v_charset == 'geostd8')) echo 'selected'; ?>>
                    geostd8</option>
                <option value=cp932 <?php if ((!empty($v_charset)) && ($v_charset == 'cp932')) echo 'selected'; ?>>
                    cp932</option>
                <option value=eucjpms <?php if ((!empty($v_charset)) && ($v_charset == 'eucjpms')) echo 'selected'; ?>>
                    eucjpms</option>
            </select>
        </div>

        <label for="v_db_email">Send login credentials to email address</label>
        <div class="input-group mb-3">
            <input type="text" name="v_db_email" class="form-control" placeholder="Send login credentials to email address">
        </div>

        <div class="row">
            <!-- /.col -->

            <!-- /.col -->
        </div>

        <button type="submit" class="btn btn-primary btn-block">Confirm</button>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db" class="btn btn-default btn-block">Back</a>
        <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
        <input type="hidden" name="ok" value="Add">

    </form>
</div>