<p class="text-center">
    <?php
    echo $_SESSION['error_msg'];
    $_SESSION['error_msg'] = NULL;
    ?>
</p>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add Database
    </a>
    <a href="http://<?= strtok($_SERVER['HTTP_HOST'], ':') ?>/phpmyadmin" target="_blank" class="btn btn-warning">
        <i class="fas fa-database"></i> phpMyAdmin
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Databse</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="type" data-filter-control="input" data-sortable="true">Type</th>
            <th data-field="username" data-filter-control="input" data-sortable="true">Username</th>
            <th data-field="hostname" data-filter-control="input" data-sortable="true">Hostname</th>
            <th data-field="disk" data-filter-control="input" data-sortable="true">Disk</i></th>
            <th data-field="charset" data-filter-control="input" data-sortable="true">Charset</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td></td>
                <td> <b><? echo $key ?></b></td>
                <td>
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db/edit/<?php if (isset($_SESSION['look'])) {
                                                                                echo $_SESSION['look'];
                                                                            } else {
                                                                                echo $_SESSION['user'];
                                                                            } ?>/<?= $key ?>" title="Delete">
                        <i class="fas fa-pencil-alt"></i>
                    </a>&nbsp;
                    <?php if ($each['SUSPENDED'] != 'yes') { ?>
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db/suspend/<?php if (isset($_SESSION['look'])) {
                                                                                        echo $_SESSION['look'];
                                                                                    } else {
                                                                                        echo $_SESSION['user'];
                                                                                    } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Suspend">
                            <i class="fas fa-pause"></i>
                        </a>
                    <?php } else { ?>
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db/unsuspend/<?php if (isset($_SESSION['look'])) {
                                                                                        echo $_SESSION['look'];
                                                                                    } else {
                                                                                        echo $_SESSION['user'];
                                                                                    } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Unsuspend">
                            <i class="fas fa-play"></i>
                        </a>
                    <?php } ?>
                    &nbsp;

                    <a href="" data-toggle="modal" data-target="#exampleModalLong" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal danger" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure want to delete <b><?= $key ?></b> .
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/db/delete/<?php if (isset($_SESSION['look'])) {
                                                                                                                        echo $_SESSION['look'];
                                                                                                                    } else {
                                                                                                                        echo $_SESSION['user'];
                                                                                                                    } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Delete">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><? echo $each['TYPE'] ?></td>
                <td><? echo $each['DBUSER'] ?></td>
                <td><? echo $each['HOST'] ?></td>
                <td><? echo $each['U_DISK'] ?></td>
                <td><? echo $each['CHARSET'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php
// echo "<pre>", print_r($data, true);
?>