<div class="col-4">
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>
    <form name="v_edit_dns" action="https://<?= $_SERVER['HTTP_HOST'] ?>/ip/edit/<?= $v_ip ?>" method="post">

        <label for="v_ip">IP</label>
        <div class="input-group mb-3">
            <input type="text" name="v_ip" class="form-control" value="<?= $v_ip ?>" disabled>
            <input type="hidden" name="v_ip" value="<?= $v_ip ?>">
        </div>

        <label for="v_netmask">Netmask</label>
        <div class="input-group mb-3">
            <input type="text" name="v_netmask" class="form-control" value="<?= $v_netmask ?>" disabled>
            <input type="hidden" name="v_netmask" value="<?= $v_netmask ?>">
        </div>

        <label for="v_interace">Interface</label>
        <div class="input-group mb-3">
            <input type="text" name="v_interace" class="form-control" value="<?= $v_interace ?>" disabled>
            <input type="hidden" name="v_interace" value="<?= $v_interace ?>">
        </div>

        <div class="input-group form-control mb-3">
            <input type="checkbox" name="v_dns" id="dns" checked=yes>
            <label class="" for="dns"> &nbsp; Shared</label>
        </div>

        <label for="v_name">Assigned domain</label>&emsp;<em>(<?= __("Optional") ?>)</em>
        <div class="input-group mb-3">
            <input type="text" name="v_name" class="form-control" value="<?= $v_name ?>">
        </div>

        <label for="v_nat">NAT IP association</label>&emsp;<em>(<?= __("Optional") ?>)</em>
        <div class="input-group mb-3">
            <input type="text" name="v_nat" class="form-control" value="<?= $v_nat ?>">
        </div>

        <button type="submit" class="btn btn-primary btn-block">Confirm</button>

        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/ip" class="btn btn-default btn-block">Back</a>

        <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
        <input type="hidden" name="save" value="save">
    </form>
</div>
<?php
    // echo "<pre>", print_r($data);
