<?php

/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.
 *
 * @category   Kumbia
 * @package    Db
 * @subpackage Adapters
 *
 * @copyright  Copyright (c) 2005 - 2019 KumbiaPHP Team (http://www.kumbiaphp.com)
 * @license    https://github.com/KumbiaPHP/KumbiaPHP/blob/master/LICENSE   New BSD License
 */

/**
 * MySQL Improved Database Support.
 *
 * @category   Kumbia
 * @package    Db
 * @subpackage Adapters
 */
class DbMySQL extends DbBase implements DbBaseInterface
{
    /**
     * MySQL Connection Resource.
     *
     * @var resource
     */
    public $id_connection;
    /**
     * Last Result of a Query.
     *
     * @var resource
     */
    public $last_result_query;
    /**
     * Last SQL statement sent to MySQL.
     *
     * @var string
     */
    protected $last_query;
    /**
     * Last error generated by MySQL.
     *
     * @var string
     */
    public $last_error;

    /**
     * Associative Array Result.
     */
    const DB_ASSOC = MYSQLI_ASSOC;

    /**
     * Result of Associative and Numerical Array.
     */
    const DB_BOTH = MYSQLI_BOTH;

    /**
     * Array Numerical result.
     */
    const DB_NUM = MYSQLI_NUM;

    /**
     * Integer Data Type.
     */
    const TYPE_INTEGER = 'INTEGER';

    /**
     * Data Type Date.
     */
    const TYPE_DATE = 'DATE';

    /**
     * Varchar Data Type.
     */
    const TYPE_VARCHAR = 'VARCHAR';

    /**
     * Decimal Data Type.
     */
    const TYPE_DECIMAL = 'DECIMAL';

    /**
     * Datetime Data Type.
     */
    const TYPE_DATETIME = 'DATETIME';

    /**
     * Data Type Char.
     */
    const TYPE_CHAR = 'CHAR';

    /**
     * Makes a connection to the MySQL database.
     *
     * @param array $config
     *
     * @return bool
     */
    public function connect(array $config)
    {
        if (!extension_loaded('mysqli')) {
            throw new KumbiaException('You must load the PHP extension called php_mysqli');
        }
        $this->id_connection = new mysqli($config['host'], $config['username'], $config['password'], $config['name'], $config['port']);
        //$object-> error() is not used since it only works from 5.2.9 and 5.3
        if (mysqli_connect_error()) {
            throw new KumbiaException(mysqli_connect_error());
        }
        //Select charset
        if (isset($config['charset'])) {
            $this->id_connection->set_charset($config['charset']);
        }

        return true;
    }

    /**
     * Performs SQL operations on the database.
     *
     * @param string $sql_query
     *
     * @return resource or false
     */
    public function query($sql_query)
    {
        $this->debug($sql_query);
        if ($this->logger) {
            Logger::debug($sql_query);
        }

        $this->last_query = $sql_query;
        if ($result_query = mysqli_query($this->id_connection, $sql_query)) {
            $this->last_result_query = $result_query;

            return $result_query;
        }
        throw new KumbiaException($this->error(" when executing <em>\"$sql_query\"</em>"));
    }

    /**
     * Close the Database Engine Connection.
     *
     * @return bool
     */
    public function close()
    {
        if ($this->id_connection) {
            return mysqli_close($this->id_connection);
        }
    }

    /**
     * Returns the content of a select row by row.
     *
     * @param resource $result_query
     * @param int      $opt
     *
     * @return array
     */
    public function fetch_array($result_query = '', $opt = MYSQLI_BOTH)
    {
        if (!$result_query) {
            $result_query = $this->last_result_query;
            if (!$result_query) {
                return false;
            }
        }

        return mysqli_fetch_array($result_query, $opt);
    }

    /**
     * Class Builder
     *
     * @param array $config
     */
    public function __construct($config)
    {
        $this->connect($config);
    }

    /**
     * Returns the number of rows of a select.
     */
    public function num_rows($result_query = '')
    {
        if (!$result_query) {
            $result_query = $this->last_result_query;
            if (!$result_query) {
                return false;
            }
        }
        if (($number_rows = mysqli_num_rows($result_query)) !== false) {
            return $number_rows;
        }
        throw new KumbiaException($this->error());
    }

    /**
     * Returns the name of a field in the result of a select.
     *
     * @param int      $number
     * @param resource $result_query
     *
     * @return string
     */
    public function field_name($number, $result_query = '')
    {
        if (!$result_query) {
            $result_query = $this->last_result_query;
            if (!$result_query) {
                return false;
            }
        }
        if ((mysqli_field_seek($result_query, $number)) !== false) {
            $field = mysqli_fetch_field($result_query);

            return $field->name;
        }
        throw new KumbiaException($this->error());
    }

    /**
     * It moves to the result indicated by 3 in a select.
     *
     * @param int      $number
     * @param resource $result_query
     *
     * @return bool
     */
    public function data_seek($number, $result_query = '')
    {
        if (!$result_query) {
            $result_query = $this->last_result_query;
            if (!$result_query) {
                return false;
            }
        }
        if (($success = mysqli_data_seek($result_query, $number)) !== false) {
            return $success;
        }
        throw new KumbiaException($this->error());
    }

    /**
     * Number of rows affected in an insert, update or delete.
     *
     * @param resource $result_query
     *
     * @return int
     */
    public function affected_rows($result_query = '')
    {
        if (($numberRows = mysqli_affected_rows($this->id_connection)) !== false) {
            return $numberRows;
        }
        throw new KumbiaException($this->error());
    }

    /**
     * Returns the MySQL error.
     *
     * @return string
     */
    public function error($err = '')
    {
        $this->last_error = mysqli_error($this->id_connection) ?: '[Unknown Error in MySQLi]';
        $this->last_error .= $err;
        if ($this->logger) {
            Logger::error($this->last_error);
        }

        return $this->last_error;
    }

    /**
     * Returns the MySQL error number.
     *
     * @return int
     */
    public function no_error()
    {
        return mysqli_errno($this->id_connection);
    }

    /**
     * Returns the last autonomic id generated in the database.
     *
     * @return int
     */
    public function last_insert_id($table = '', $primary_key = '')
    {
        return mysqli_insert_id($this->id_connection);
    }

    /**
     * Check if a table exists or not.
     *
     * @param string $table
     *
     * @return bool
     */
    public function table_exists($table, $schema = '')
    {
        $table = addslashes("$table");
        $sql = "select count(*) from information_schema.tables where table_name = '$table'";
        if ($schema) {
            $schema = addslashes("$schema");
            $sql .= " and table_schema = '$schema'";
        }

        return $this->fetch_one($sql)[0];
    }

    /**
     * Returns a valid LIMIT for a SELECT of the RBDM.
     *
     * @param string $sql consulta sql
     *
     * @return string
     */
    public function limit($sql)
    {
        $params = Util::getParams(func_get_args());

        if (isset($params['limit']) && is_numeric($params['limit'])) {
            $sql .= " LIMIT $params[limit]";
        }

        if (isset($params['offset']) && is_numeric($params['offset'])) {
            $sql .= " OFFSET $params[offset]";
        }

        return $sql;
    }

    /**
     * Delete a table from the database.
     *
     * @param string $table
     *
     * @return resource
     */
    public function drop_table($table, $if_exists = true)
    {
        if ($if_exists) {
            return $this->query("DROP TABLE IF EXISTS $table");
        }

        return $this->query("DROP TABLE $table");
    }

    /**
     * Create a table using RDBM native SQL.
     *
     * EVERYTHING:
     * - The index parameter needs to work. This should list multipes and unique composite indices
     * - Add the type of table to use (MySQL)
     * - Support for autonomous fields
     * - Foreign key holder
     *
     * @param string $table
     * @param array  $definition
     *
     * @return resource
     */
    public function create_table($table, $definition, $index = array())
    {
        $create_sql = "CREATE TABLE $table (";
        if (!is_array($definition)) {
            throw new KumbiaException("Invalid definition to create the table '$table'");
        }
        $create_lines = array();
        $index = array();
        $unique_index = array();
        $primary = array();

        foreach ($definition as $field => $field_def) {
            if (isset($field_def['not_null'])) {
                $not_null = $field_def['not_null'] ? 'NOT NULL' : '';
            } else {
                $not_null = '';
            }
            if (isset($field_def['size'])) {
                $size = $field_def['size'] ? '(' . $field_def['size'] . ')' : '';
            } else {
                $size = '';
            }
            if (isset($field_def['index']) && $field_def['index']) {
                $index[] = "INDEX(`$field`)";
            }
            if (isset($field_def['unique_index']) && $field_def['unique_index']) {
                $index[] = "UNIQUE(`$field`)";
            }
            if (isset($field_def['primary']) && $field_def['primary']) {
                $primary[] = "`$field`";
            }
            if (isset($field_def['auto']) && $field_def['auto']) {
                $field_def['extra'] = isset($field_def['extra']) ? $field_def['extra'] . ' AUTO_INCREMENT' : 'AUTO_INCREMENT';
            }
            if (isset($field_def['extra'])) {
                $extra = $field_def['extra'];
            } else {
                $extra = '';
            }
            $create_lines[] = "`$field` " . $field_def['type'] . $size . ' ' . $not_null . ' ' . $extra;
        }
        $create_sql .= join(',', $create_lines);
        $last_lines = array();
        if (count($primary)) {
            $last_lines[] = 'PRIMARY KEY(' . join(',', $primary) . ')';
        }
        if (count($index)) {
            $last_lines[] = join(',', $index);
        }
        if (count($unique_index)) {
            $last_lines[] = join(',', $unique_index);
        }
        if (count($last_lines)) {
            $create_sql .= ',' . join(',', $last_lines) . ')';
        }

        return $this->query($create_sql);
    }

    /**
     * List the tables in the database.
     *
     * @return array
     */
    public function list_tables()
    {
        return $this->fetch_all('SHOW TABLES');
    }

    /**
     * List the fields of a table.
     *
     * @param string $table
     *
     * @return array
     */
    public function describe_table($table, $schema = '')
    {
        if ($schema) {
            return $this->fetch_all("DESCRIBE `$schema`.`$table`");
        }

        return $this->fetch_all("DESCRIBE `$table`");
    }

    /**
     * Returns the last sql statement executed by the Adapter.
     *
     * @return string
     */
    public function last_sql_query()
    {
        return $this->last_query;
    }
}
