<div id="scaffold">
    <?php View::content() ?>
    <h1>
        <?= ucwords("$model"), ": <span>$action_name</span>" ?>
    </h1>

    <div class="col-8 offset-2">
        <?php ModelForm::create($model) ?>
    </div>

    <div class="col-12">
        <a href="../" class="btn btn-default">List</a>
    </div>
    <?php //View::partial('editors/tinymce') // Will we see if we include any wysiwyg
    ?>
</div>