<div id="scaffold">
    <?php View::content() ?>
    <h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
    <div class="actions">
        <?= Html::linkAction("create/", 'Create record', 'class="btn btn-primary"') ?>
    </div>
    <?php if (isset($data->items) && (count($data->items) > 0)) : ?>
        <table class="t">
            <thead>
                <tr>
                    <?php foreach (current($data->items)->fields as $field) : ?>
                        <th><?= (current($data->items)->get_alias($field)) ?></th>
                    <?php endforeach ?>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data->items as $item) : ?>
                    <tr>
                        <?php foreach ($item->fields as $field) : ?>
                            <td><?= h($item->$field) ?></td>
                        <?php endforeach ?>
                        <td><?= Html::linkAction("view/$item->id", 'See') ?> |
                            <?= Html::linkAction("edit/$item->id", 'Edit') ?> |
                            <?= Html::linkAction("delete/$item->id", 'Delete', 'onclick="return confirm(\'Are you sure?\')"') ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php View::partial('paginators/digg', false, array('page' => $data, 'url' => Router::get('controller_path') . '/index')) ?>

    <?php else : // If there are no items
    ?>
        <h2>There is no record</h2>
    <?php endif ?>
</div>