<div id="scaffold">
	<?php View::content() ?>
	<?php if ($data) : ?>
		<h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
		<ul>
			<?php foreach ($data->fields as $field) : ?>
				<li><strong><?= $data->alias[$field] ?> :</strong> <?= h($data->$field) ?></li>
			<?php endforeach ?>
		</ul>

		<div class="actions">
			<a href="../" class="btn btn-default">List</a>
			<a href="../create/" class="btn btn-primary">Create record</a>
			<a href="../edit/<?= $data->id ?>" class="btn btn-warning">Edit</a>
			<a class="del btn btn-danger" title="Are you sure you want to delete?" href="../delete/<?= $data->id ?>" onclick="return confirm('Are you sure?');">Delete</a>
		</div>
	<?php else : ?>
		<?php http_response_code(404) ?>
		<h1>Does not exist</h1>
		<div class="actions">
			<a href="../">List</a>
			<a href="../create/">Create record</a>
		</div>
	<?php endif ?>
</div>