<div class="hero">
    <h2> KumbiaPHP <?= kumbia_version() ?> is ready to use </h2>
    <h3> Welcome to KumbiaPHP Framework </h3>
    <p> The framework is now ready to develop web applications with PHP, quickly and easily, without having to reinvent the wheel, and worrying most importantly, the logic of your application. </p>
    <?= Html::link('pages/kumbia/status/', 'View Config', 'title="See application settings" class="btn btn-info"') ?>
</div>
<h2> How to get started </h2>
     <p> In our <a href="http://wiki.kumbiaphp.com/"> wiki </a> you can find updated information on the use of the framework, if you are starting with <em>KumbiaPHP</em> you should do the
    <strong>
        <a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Hello World application</a>
    </strong>.
</p>
<p>You may also be interested to know about:</p>
<ul>
    <li><a href="http://wiki.kumbiaphp.com/V1.0_CRUD_en_KumbiaPHP_Framework">Creation of CRUD (Create, Read, Update, Delete)</a></h3>
    </li>
    <li><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Use of models</a></li>
    <li><a href="https://github.com/KumbiaPHP/Documentation/blob/master/es/active-record.md#configurando-conexi%C3%B3n-a-la-base-de-datos">Configure database connections</a></li>
</ul>
<p>These are just some examples, you can see more in the <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">wiki tutorial section</a></p>
<?php
// echo "<pre>", print_r($_SESSION);
