<?php

/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.
 * 
 * "Classic" pager for applications
 *
 * Pager parameters:
 *   page: object obtained by invoking the pager
 *   show: number of pages to be displayed on the pager
 *   url: url for the action performed by the page, by default "module / controller / page /"
 *        and the page number is sent by parameter
 *
 * @category    Kumbia
 * @package     Partials
 * @subpackage  Paginators
 *
 * @copyright  Copyright (c) 2005 - 2019 KumbiaPHP Team (http://www.kumbiaphp.com)
 * @license    https://github.com/KumbiaPHP/KumbiaPHP/blob/master/LICENSE   New BSD License
 */

if (!isset($url)) {
    extract(Router::get());
    $url = "$controller/page";
    if ($module) {
        $url = "$module/$url";
    }
}

if (!isset($show)) {
    $show = 10;
}

$half = floor($show / 2);

// Calculating the start of centered pager
if ($page->current <= $half) {
    $start = 1;
} elseif (($page->total - $page->current) < $half) {
    $start = $page->total - $show + 1;
    if ($start < 1) $start = 1;
} else {
    $start = $page->current - $half;
}
?>

<div class="paginator">
    <?php if ($page->prev == 1) echo Html::link("$url/", 'Previous', 'title="Go to previous" class="nextprev" rel="prev"'); // The link is placed without page number for page 1
    elseif ($page->prev) echo Html::link("$url/$page->prev/", 'Previous', 'title="Go to previous" class="nextprev" rel="prev"') ?>

    <?php if ($start == 1) { //the link without page number is placed for page 1
        $start = 2;
        $show -= 1;
        echo $page->current == 1 ? "<strong>1</strong>" : Html::link("$url/", '1');
    } ?>

    <?php for ($i = $start; $i <= $page->total && $i < ($start + $show); $i++) : ?>
        <?= $i == $page->current ? "<strong>$i</strong>" : Html::link("$url/$i/", $i) ?>
    <?php endfor ?>

    <?php if ($page->next) echo Html::link("$url/$page->next/", 'Next', 'title="Go to next" class="nextprev" rel="next"') ?>
</div>