<body>

    <title>Edit Mail Account</title>

    <div class="col-4">
        <p class="login-box-msg"><b>Editing Mail Account</b></p>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['okr_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>

        <form name="v_edit_mail_acc" action="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/editmailacc/<?php if (isset($_SESSION['look'])) {
                                                                                                        echo $_SESSION['look'];
                                                                                                    } else {
                                                                                                        echo $_SESSION['user'];
                                                                                                    } ?>/<?= htmlentities(trim($v_domain, "'")) ?>/<?= htmlentities(trim($v_account, "'")) ?>" method="post">
            <label for="v_account">Account</label>
            <div class="input-group mb-3">
                <input type="text" name="v_account" class="form-control" value="<?php echo htmlentities(trim($v_account, "'")), '@', htmlentities(trim($v_domain, "'")); ?>" disabled>
                <input type="hidden" name="v_domain" value="<?= htmlentities(trim($v_domain, "'")) ?>">
                <input type="hidden" name="v_account" value="<?= htmlentities(trim($v_account, "'")) ?>">
            </div>

            <label for="v_password">Password</label>
            <div class="input-group mb-3">
                <input type="text" name="v_password" class="form-control" value="<?= htmlentities(trim($v_password, "'")) ?>">
            </div>

            <label for="v_quota">Quota (in megabytes)</label>
            <div class="input-group mb-3">
                <input type="text" name="v_quota" class="form-control" value="<?= htmlentities(trim($v_quota, "'")) ?>" disabled>
            </div>

            <label for="v_aliases">Aliases (use local-part)</label>
            <div class="input-group mb-3">
                <textarea size="20" class="form-control" name="v_aliases"><?= htmlentities(trim($v_aliases, "'")) ?></textarea>
            </div>

            <label for="v_aliases">Forward to (one or more email addresses)</label>
            <div class="input-group mb-3">
                <textarea size="20" class="form-control" name="v_fwd"><?= htmlentities(trim($v_fwd, "'")) ?></textarea>
            </div>

            <div class="input-group form-control mb-3">
                <input type="checkbox" name="v_fwd_only" id="v_fwd_only" <?php if ($v_fwd_only == 'yes') echo "checked=yes" ?>>
                <label for="antivirus"> &nbsp; Do not store forwarded mail </label>
            </div>

            <div class="input-group form-control mb-3">
                <input type="checkbox" name="v_autoreply" id="v_autoreply" <?php if ($v_autoreply == 'yes') echo "checked=yes" ?>>
                <label for="antivirus"> &nbsp; Autoreply </label>
            </div>

            <table style="display:<?php if ($v_autoreply == 'yes') {
                                        echo 'block';
                                    } else {
                                        echo 'none';
                                    } ?> ;" id="autoreplytable">
                <tr>
                    <td class="vst-text" style="padding: 12px 0 0 0;">
                        <?php print __('Message'); ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <textarea size="20" class="vst-textinput" name="v_autoreply_message"><?= htmlentities(trim($v_autoreply_message, "'")) ?></textarea>
                    </td>
                </tr>
            </table>
            <label for="v_aliases">Send login credentials to email address</label>
            <div class="input-group mb-3">
                <input type="text" name="v_send_email" class="form-control" value="<?= htmlentities(trim($v_send_email, "'")) ?>">
                <input type="hidden" name="v_credentials" id="v_credentials">
            </div>

            <div class="row">
                <!-- /.col -->
                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/listmailacc" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">

        </form>
    </div>

</body>

<?php
// echo "mail/add", "<pre>", print_r($data, true);
