<p class="text-center">
    <?php
    echo $_SESSION['error_msg'];
    $_SESSION['error_msg'] = NULL;
    ?>
</p>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add Mail Domain
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="domain" data-filter-control="input" data-sortable="true">Domain</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="account" data-filter-control="input" data-sortable="true">Accounts</th>
            <th data-field="antivirus" data-filter-control="input" data-sortable="true" title="Disk">Anti-Virus</th>
            <th data-field="bandwidth" data-filter-control="input" data-sortable="true" title="Bandwidth">Spam Filter</th>
            <th data-field="dkim" data-filter-control="input" data-sortable="true" title="SSL">DKIM</th>
            <th data-field="ssl" data-filter-control="input" data-sortable="true">SSL</th>
            <th data-field="catchall" data-filter-control="input" data-sortable="true">Catchall Mail</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td></td>
                <td> <b><? echo $key ?></b></td>
                <td>
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/listmailacc/<?= $key ?>" title="List Mail Acoounts">
                        <i class="fas fa-list status-icon lightblue status-icon dim"></i>
                    </a>
                    &nbsp;
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/addmailacc/<?= $key ?>" title="Add Mail Account">
                        <i class="fas fa-plus-circle status-icon"></i>
                    </a>
                    &nbsp;
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/edit/<?php if (isset($_SESSION['look'])) {
                                                                                echo $_SESSION['look'];
                                                                            } else {
                                                                                echo $_SESSION['user'];
                                                                            } ?>/<?= $key ?>" title="Edit Mail Domain" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <?php if ($_SESSION['user'] == 'admin') {

                        if ($each['SUSPENDED'] != 'yes') { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/suspend/<?= $key ?>//<?= $_SESSION['token']; ?>" title="Suspend">
                                <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                        <?php } else { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/unsuspend/<?= $key ?>//<?= $_SESSION['token']; ?>" title="Unsuspend">
                                <i class="fas fa-play status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                    <?php }
                    } ?>

                    <a href="" data-toggle="modal" data-target="#exampleModalLong" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal danger" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure want to delete <b><?= $key ?></b> .
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/delete/<?php if (isset($_SESSION['look'])) {
                                                                                                                            echo $_SESSION['look'];
                                                                                                                        } else {
                                                                                                                            echo $_SESSION['user'];
                                                                                                                        } ?>/<?= $key ?>//<?= $_SESSION['token'] ?>" title="Delete">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><? echo $each['ACCOUNTS'] ?></td>
                <td><? echo $each['ANTIVIRUS'] ?></td>
                <td><? echo $each['ANTISPAM'] ?></td>
                <td><? echo $each['DKIM'] ?></td>
                <td><? echo $each['STATS'] ?></td>
                <td><? echo $each['CATCHALL'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>