<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>
<p class="text-center">
    <?php
    echo $_SESSION['error_msg'];
    $_SESSION['error_msg'] = NULL;
    ?>
</p>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add Mail Domain
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="domain" data-filter-control="input" data-sortable="true">Domain</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="account" data-filter-control="input" data-sortable="true">Accounts</th>
            <th data-field="antivirus" data-filter-control="input" data-sortable="true" title="Disk">Anti-Virus</th>
            <th data-field="bandwidth" data-filter-control="input" data-sortable="true" title="Bandwidth">Spam Filter</th>
            <th data-field="dkim" data-filter-control="input" data-sortable="true" title="SSL">DKIM</th>
            <th data-field="ssl" data-filter-control="input" data-sortable="true">SSL</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
                <td> <b><? echo $key ?></b></td>
                <td>
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/listmailacc/<?= $key ?>" title="List Mail Acoounts">
                        <i class="fas fa-list status-icon lightblue status-icon dim"></i>
                    </a>
                    &nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/addmailacc/<?= $key ?>" title="Add Mail Account">
                        <i class="fas fa-plus-circle status-icon"></i>
                    </a>
                    &nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/edit/<?php if (isset($_SESSION['look'])) {
                                                                                                echo $_SESSION['look'];
                                                                                            } else {
                                                                                                echo $_SESSION['user'];
                                                                                            } ?>/<?= $key ?>" title="Edit Mail Domain" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <a class="like" href="" title="Suspend">
                        <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                    </a>
                    &nbsp;
                    <a class="remove" href="" title="Delete">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
                <td><? echo $each['ACCOUNTS'] ?></td>
                <td><? echo $each['ANTIVIRUS'] ?></td>
                <td><? echo $each['ANTISPAM'] ?></td>
                <td><? echo $each['DKIM'] ?></td>
                <td><? echo $each['STATS'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

</div>

<?php
// echo "<pre>", print_r($data, true);
?>