<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>

<div id="toolbar">
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/addmailacc/<?= $domain ?>" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add Mail Account
    </a>
    &nbsp;
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="account" data-filter-control="input" data-sortable="true">Account</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="disk" data-filter-control="input" data-sortable="true">Disk</th>
            <th data-field="quota" data-filter-control="input" data-sortable="true">Quota</th>
            <th data-field="forward" data-filter-control="input" data-sortable="true">Forward to</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td></td>
                <td> <b><? echo $key, "@", $domain; ?></b></td>
                <td>
                    <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/editmailacc/<?php if (isset($_SESSION['look'])) {
                                                                                                    echo $_SESSION['look'];
                                                                                                } else {
                                                                                                    echo $_SESSION['user'];
                                                                                                } ?>/<?= $domain ?>/<?= $key ?>/" title="Edit Mail Domain" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <?php if ($_SESSION['user'] == 'admin') {
                        if ($each['SUSPENDED'] != 'yes') { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/suspend/<?= $domain ?>/<?= $key ?>/<?= $_SESSION['token']; ?>" title="Suspend">
                                <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                        <?php } else { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/unsuspend/<?= $domain ?>/<?= $key ?>/<?= $_SESSION['token']; ?>" title="Unsuspend">
                                <i class="fas fa-play status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                    <?php }
                    } ?>
                    <a href="" data-toggle="modal" data-target="#exampleModalLong" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal danger" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure want to delete <b><?= $key ?>@<?= $domain ?></b> .
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail/delete/<?php if (isset($_SESSION['look'])) {
                                                                                                                            echo $_SESSION['look'];
                                                                                                                        } else {
                                                                                                                            echo $_SESSION['user'];
                                                                                                                        } ?>/<?= $domain ?>/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Delete">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><? echo $each['U_DISK'] ?></td>
                <td><? echo $each['QUOTA'] ?></td>
                <td><? echo $each['FWD'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

</div>

<?php
//echo "<pre>", print_r($data);
