    <title>Reset Password</title>

    <p class="login-box-msg"><b>Reset Password</b></p>
    <p class="text-danger text-center">
        <?php
        echo $_SESSION['error_msg'];
        $_SESSION['error_msg'] = NULL;

        ?>
    </p>
    <form action="https://<?= $_SERVER['HTTP_HOST'] ?>/reset/r1" method="post">
        <div class="input-group mb-3">
            <input type="text" name="user" class="form-control" placeholder="Username">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-user"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
            </div>
            <!-- /.col -->
            <!-- /.col -->
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/login" class="btn btn-default btn-block">Back</a>
        </div>
    </form>