    <title>Reset Password</title>

    <p class="login-box-msg"><b>Reset Code</b></p>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'];
        $_SESSION['error_msg'] = NULL;
        ?>
    </p>
    <form action="<?= $_SERVER['REMOTE_HOST'] ?>" method="post">
        <div class="input-group mb-3">
            <input type="text" name="user" class="form-control" placeholder="Reset code">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-unlock-alt"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p>Password reset code has been sent to your email address</p>
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="<?= $_SERVER['REMOTE_HOST'] ?>/reset" class="btn btn-default btn-block">Back</a>
        </div>
        <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
    </form>