    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>

    <body>
        <?
        // echo "<pre>", print_r($data, true), "</pre>";
        ?>

        <title>Add User</title>

        <div class="col-4">
            <p class="login-box-msg"><b>Adding DNS</b></p>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'];
                $_SESSION['error_msg'] = NULL;
                ?>
            </p>

            <form name="v_add_user" action="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/add" method="post">
                <div class="input-group mb-3">
                    <input type="text" name="v_username" class="form-control" placeholder="Domain">
                </div>
                <div class="input-group mb-3">
                    <select name="v_package" class="form-control">
                        <?php
                        foreach ($data as $key => $value) { ?>
                            <option value="<?= $key ?>">IP Address</option>
                            <option value="<?= $key ?>"><?= $key; ?></option>
                        <?php } ?>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-block">Confirm</button>
                <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reset" class="btn btn-default btn-block">Back</a>
                <!-- <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reset" class="btn btn-default btn-block">Back</a> -->
                <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            </form>
        </div>

    </body>


    </html>

    <?php
    // echo "<pre>", print_r($data);
