<div class="col-4">
    <p class="login-box-msg"><b>Adding DNS</b></p>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
        $_SESSION['error_msg'] = NULL;
        $_SESSION['ok_msg'] = NULL;
        ?>
    </p>

    <form name="v_add_dns" action="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/add" method="post">

        <label for="v_domain">Domain</label> <span style="color:red">*</span>
        <div class="input-group mb-3">
            <input type="text" name="v_domain" class="form-control" placeholder="Domain" required>
        </div>
        <label for="v_ip">IP</label> <span style="color:red">*</span>
        <div class="input-group mb-3">
            <input type="text" name="v_ip" class="form-control" placeholder="IP" required>
        </div>


        <div class="input-group mb-3">
            <b><u><a href="javascript:elementHideShow('advtable');" style="text-decoration: none;color : #000;">Advanced options</a></u></b>
        </div>

        <table style="display:<?php if (empty($v_adv)) echo 'none'; ?> ;" id="advtable">
            <tr>
                <td class="vst-text input-label">
                    <?php print __('Expiration Date'); ?> <span class="optional">(<?= __('YYYY-MM-DD'); ?>)</span>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" size="20" class="vst-input" name="v_exp" value="<?= htmlentities(trim($v_exp, "'")) ?>">
                </td>
            </tr>
            <tr>
                <td class="vst-text input-label">
                    TTL
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" size="20" class="vst-input" name="v_ttl" value="<?= htmlentities(trim($v_ttl, "'")) ?>">
                </td>
            </tr>
            <tr>
                <td class="vst-text input-label">
                    <?php print __('Name servers'); ?>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" size="20" class="vst-input" name="v_ns1" value="<?= htmlentities(trim($v_ns1, "'")) ?>">
                    <span class="remove-ns additional-control delete"><?= __('delete') ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" size="20" class="vst-input" name="v_ns2" value="<?= htmlentities(trim($v_ns2, "'")) ?>">
                    <span class="remove-ns additional-control delete"><?= __('delete') ?></span>
                </td>
            </tr>
            <? if ($v_ns3)
                echo '<tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_ns3" value="' . htmlentities(trim($v_ns3, "'")) . '">
                                <span class="remove-ns additional-control delete">' . __('delete') . '</span>
                            </td>
                        </tr>';

            if ($v_ns4)
                echo '<tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_ns4" value="' . htmlentities(trim($v_ns4, "'")) . '">
                                <span class="remove-ns additional-control delete">' . __('delete') . '</span>
                            </td>
                        </tr>';

            if ($v_ns5)
                echo '<tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_ns5" value="' . htmlentities(trim($v_ns5, "'")) . '">
                                <span class="remove-ns additional-control delete">' . __('delete') . '</span>
                            </td>
                        </tr>';

            if ($v_ns6)
                echo '<tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_ns6" value="' . htmlentities(trim($v_ns6, "'")) . '">
                                <span class="remove-ns additional-control delete">' . __('delete') . '</span>
                            </td>
                        </tr>';

            if ($v_ns7)
                echo '<tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_ns7" value="' . htmlentities(trim($v_ns7, "'")) . '">
                                <span class="remove-ns additional-control delete">' . __('delete') . '</span>
                            </td>
                        </tr>';

            if ($v_ns8)
                echo '<tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_ns8" value="' . htmlentities(trim($v_ns8, "'")) . '">
                                <span class="remove-ns additional-control delete">' . __('delete') . '</span>
                            </td>
                        </tr>';
            ?>
            <tr class="add-ns" <? if ($v_ns8) echo 'style="display:none;"'; ?>>
                <td class="step-top-small">
                    <span class="add-ns-button additional-control add"><?= __('Add one more Name Server') ?></span>
                </td>
            </tr>

        </table>

        <button type="submit" class="btn btn-primary btn-block">Confirm</button>

        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns" class="btn btn-default btn-block">Back</a>

        <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
        <input type="hidden" name="ok" value="Add">

    </form>
</div>
<?php
// echo "<pre>", print_r($data);
