<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>
<p class="text-center">
    <?php
    echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
    $_SESSION['error_msg'] = NULL;
    $_SESSION['ok_msg'] = NULL;
    ?>
</p>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>

    <?php
    $uri = explode('/', $_SERVER['REQUEST_URI']);
    ?>
    <?php
    if (isset($uri[3])) { ?>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/addrecord/<?= $uri[3] ?>" id="add" class="btn btn-primary">
            <i class="fas fa-plus-circle status-icon"></i> Add DNS Record
        </a>&nbsp;
    <?php } else {
    ?>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/add" id="add" class="btn btn-primary">
            <i class="fas fa-plus-circle status-icon"></i> Add DNS Domain
        </a>&nbsp;
    <?php
    }
    ?>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Domain</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="revords" data-filter-control="input" data-sortable="true">Records</th>
            <th data-field="template" data-filter-control="input" data-sortable="true">Template</th>
            <th data-field="ttl" data-filter-control="input" data-sortable="true">TTL</i></th>
            <th data-field="soa" data-filter-control="input" data-sortable="true">SOA</th>
            <th data-field="exp" data-filter-control="input" data-sortable="true" title="SSL">Expiration Date</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
                <td> <b><? echo $key ?></b></td>
                <td style="text-align:center">
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/edit/<?php if (isset($_SESSION['look'])) {
                                                                                            echo $_SESSION['look'];
                                                                                        } else {
                                                                                            echo $_SESSION['user'];
                                                                                        } ?>/<?= $key ?>" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/listrecord/<?= $key ?>" title="List DNS">
                        <i class="fas fa-list-alt status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/addrecord/<?= $key ?>" title="Add DNS Record">
                        <i class="fas fa-plus-circle status-icon"></i>
                    </a>
                    &nbsp;
                    <?php if ($_SESSION['user'] == 'admin') {
                        if ($each['SUSPENDED'] != 'yes') { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/suspend/<?php if (isset($_SESSION['look'])) {
                                                                                                            echo $_SESSION['look'];
                                                                                                        } else {
                                                                                                            echo $_SESSION['user'];
                                                                                                        } ?>/<?= $key ?>//<?= $_SESSION['token']; ?>" title="Suspend">
                                <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                        <?php } else { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/unsuspend/<?php if (isset($_SESSION['look'])) {
                                                                                                            echo $_SESSION['look'];
                                                                                                        } else {
                                                                                                            echo $_SESSION['user'];
                                                                                                        } ?>/<?= $key ?>//<?= $_SESSION['token']; ?>" title="Unsuspend">
                                <i class="fas fa-play status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                    <?php }
                    } ?>
                    <a class="like" href="" data-toggle="modal" data-target="#exampleModalLong" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal danger" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure want to delete <b><?= $key ?></b> .
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/deletedomain/<?php if (isset($_SESSION['look'])) {
                                                                                                                                echo $_SESSION['look'];
                                                                                                                            } else {
                                                                                                                                echo $_SESSION['user'];
                                                                                                                            } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Delete">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><? echo $each['RECORDS'] ?></td>
                <td><? echo $each['TPL'] ?></td>
                <td><? echo $each['TTL'] ?></td>
                <td><? echo $each['SOA'] ?></td>
                <td><? echo translate_date($each['EXP']) ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php
// echo "<pre>", print_r($data, true);
?>