<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>

<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add DNS Zone
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Domain</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="revords" data-filter-control="input" data-sortable="true">Records</th>
            <th data-field="template" data-filter-control="input" data-sortable="true">Template</th>
            <th data-field="ttl" data-filter-control="input" data-sortable="true">TTL</i></th>
            <th data-field="soa" data-filter-control="input" data-sortable="true">SOA</th>
            <th data-field="exp" data-filter-control="input" data-sortable="true" title="SSL">Expiration Date</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
                <td> <b><? echo $key ?></b></td>
                <td> <a class="like" href="javascript:void(0)" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a></td>
                <td><? echo $each['RECORDS'] ?></td>
                <td><? echo $each['TPL'] ?></td>
                <td><? echo $each['TTL'] ?></td>
                <td><? echo $each['SOA'] ?></td>
                <td><? echo translate_date($each['EXP']) ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

</div>

<?php
//echo "<pre>", print_r($data, true);
?>