<?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
        $_SESSION['error_msg'] = NULL;
        $_SESSION['ok_msg'] = NULL;
        ?>
    </p>
<?php } ?>
<div>
    <p>Listing <b><?= $uri[3]; ?></b></p>
</div>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <?php
    if (isset($uri[3])) { ?>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/addrecord/<?= $uri[3] ?>" id="add" class="btn btn-primary">
            <i class="fas fa-plus-circle status-icon"></i> Add DNS Record
        </a>
    <?php }
    ?>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="record" data-filter-control="input" data-sortable="true">Record</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="type" data-filter-control="input" data-sortable="true">Type</th>
            <th data-field="value" data-filter-control="input" data-sortable="true">IP or Value</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td></td>
                <td> <b><?= $each['RECORD'] ?></b></td>
                <td style="text-align:center">
                    &nbsp;
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/editrecord/<?php if (isset($_SESSION['look'])) {
                                                                                        echo $_SESSION['look'];
                                                                                    } else {
                                                                                        echo $_SESSION['user'];
                                                                                    } ?>/<?= $uri[3] ?>/<?= $each['ID'] ?>" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>&nbsp;

                    <a href="" data-toggle="modal" data-target="#exampleModalLong" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal danger" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure want to delete <b><?= $each['RECORD'] ?></b> .
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns/deleterecord/<?php if (isset($_SESSION['look'])) {
                                                                                                                                echo $_SESSION['look'];
                                                                                                                            } else {
                                                                                                                                echo $_SESSION['user'];
                                                                                                                            } ?>/<?= $uri[3] ?>/<?= $each['ID'] ?>/<?= $_SESSION['token'] ?>" title="Delete">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><?= $each['TYPE'] ?></td>
                <td><?= $each['VALUE'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

</div>

<?php
// echo "<pre>", print_r($data);
?>