<? include(APP_PATH . 'libs/stats.php'); ?>
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        <?= 'Executed in ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT']) * 1000, 4), ' ms. using ', number_format(memory_get_usage() / 1048576, 3), ' MB of memory'; ?> </div>
    <!-- Default to the left -->
    <strong>Powered by <a href="https://uwpanel.com">UWPanel.com</a></strong> &nbsp; | &nbsp; Server Time: <b> <?= print_r($time_data, true); ?></b> &nbsp; Time Zone: <b><?= print_r($timezone_data, true); ?> </b>
    <div class="col-12 text-center"> </div>
</footer>
</div>
<!-- ./wrapper -->

<!-- Bootstrap 4 -->
<? //= Tag::js('bootstrap.bundle.min'); 
?>
<!-- jQuery -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/jquery.min.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
<!-- Popper -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/popper.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script> -->
<!-- Bootstrap 4 -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/bootstrap.min.js"></script>
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->
<!-- AdminLTE App -->
<?= Tag::js('adminlte.min'); ?>

<!-- REQUIRED SCRIPTS -->
<?= Tag::js('app'); ?>

<!-- Bootstrap Table -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/bootstrap-table.min.js"></script>
<!-- <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script> -->
<!-- Bootstrap Table add-ons -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/tableExport.min.js"></script>
<!-- <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script> -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/bootstrap-table.min.js"></script>
<!-- <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script> -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/bootstrap-table-locale-all.min.js"></script>
<!-- <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table-locale-all.min.js"></script> -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/bootstrap-table-export.min.js"></script>
<!-- overlayScrollbars -->
<script src="https://<?= $_SERVER['HTTP_HOST'] ?>/javascript/jquery.overlayScrollbars.min.js"></script>
<?= Tag::js('misc'); ?>

<?php
$uri = explode('/', $_SERVER['REQUEST_URI']);
$controller = $uri[1];
$method = $uri[2];
if ($controller != '') {
    if (isset($controller) != NULL && isset($method) != NULL) {
        echo Tag::js('pages/' . $controller . '/' . $method);
    }
}
?>

</body>

</html>