    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            <?= 'Executed in ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT']) * 1000, 4), ' ms. using ', number_format(memory_get_usage() / 1048576, 3), ' MB of memory'; ?> </div>
        <!-- Default to the left -->
        <strong>Powered by <a href="https://uwpanel.com">UWPanel.com</a></strong>
        <div class="col-12 text-center"> </div>
    </footer>
    </div>
    <!-- ./wrapper -->

    <!-- <? //php Tag::js('jquery.min') //php is not working 
            ?> -->

    <!-- jQuery -->
    <? //= Tag::js('jquery/jquery.min'); 
    ?>

    <!-- Bootstrap 4 -->
    <? //= Tag::js('bootstrap.bundle.min'); 
    ?>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <?= Tag::js('adminlte.min'); ?>

    <!-- REQUIRED SCRIPTS -->
    <?= Tag::js('app'); ?>

    <!-- Bootstrap Table -->
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    <!-- Bootstrap Table add-ons -->
    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table-locale-all.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/export/bootstrap-table-export.min.js"></script>

    <?= Tag::js('misc'); ?>
    <?= Tag::js('pages/user/add'); ?>

    </body>

    </html>