<?php

/**
 * Header file for the Twenty Twenty WordPress default theme.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Twenty_Twenty
 * @since 1.0.0
 */

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset=<?= APP_CHARSET ?>>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>KumbiaPHP Framework</title>

    <!-- Font Awesome Icons -->
    <? //php Tag::css('all.min') 
    ?>
    <!-- Theme Stylesheet -->
    <?php Tag::css('adminlte.min') ?>
    <!-- Theme Stylesheet
    <link rel="stylesheet" href="https://<?//=$_SERVER['HTTP_HOST']?>/public/css/adminlte.min.css"> -->
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Bootsrap Min.CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <!-- Bootsrap Table -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">

    <?= Html::includeCss() ?>

    <style>
        /* Always Show Scroll Bar */
        html {
            overflow-y: scroll;
        }
    </style>

</head>

<body class="hold-transition sidebar-mini">

    <div class="wrapper">

        <?php View::partial('navbar') ?>

        <?php View::partial('sidebar') ?>