<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="position: fixed">
    <!-- Brand Logo -->
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>" class="brand-link" style="padding: 8px 5px 10px 35px;">
        <?= Html::img('uwpanel-logo-light.png', 'UWpanel', 'width="180px"') ?>
        <!-- <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <?php
        include(APP_PATH . 'libs/stats.php');
        $active = explode('/', $_SERVER['REQUEST_URI']);
        ?>
        <!-- Sidebar Menu -->
        <?php
        foreach ($stats_result as $key => $each) {
        ?>
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" style="padding-top: 10px;">
                    <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>" class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/') echo "active"; ?>">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>Dashboard
                            </p>
                        </a>
                    </li>
                    <?php if ($_SESSION['user'] == 'admin' && empty($_SESSION['look'])) { ?>
                        <li class=" nav-item ">
                            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/user" class="nav-link <?php if ($active[1] == 'user') echo "active"; ?>">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Users
                                    <?php if ($_SESSION['user'] == 'admin' && empty($_SESSION['look'])) { ?>
                                        <span class="right ">
                                            <span class=" badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Users"><?= $each['U_USERS'] ?></span>
                                            <span class=" badge badge-danger" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Suspended"><?= $each['SUSPENDED_USERS'] ?></span>
                                        </span>

                                    <? } else { ?>
                                        <span class="right">
                                            <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Disk"><?= $each['U_DISK'] ?></span>
                                            <span class="badge badge-info" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Bandwidth"><?= $each['U_BANDWIDTH'] ?></span>
                                        </span>
                                    <? } ?>
                                </p>
                            </a>
                        </li>
                    <?php } ?>
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/web" class="nav-link <?php if ($active[1] == 'web' || $active[1] == 'weblog') echo "active"; ?>">
                            <i class="nav-icon fas fa-globe"></i>
                            <p>
                                Web
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Web Domains"><?= $each['U_WEB_DOMAINS'] ?></span>
                                    <span class="badge badge-info" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Aliases"><?= $each['U_WEB_ALIASES'] ?></span>
                                    <span class="badge badge-danger" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Suspended"><?= $each['SUSPENDED_WEB'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns" class="nav-link <?php if ($active[1] == 'dns') echo "active"; ?>">
                            <i class="nav-icon fas fa-sitemap"></i>
                            <p>
                                DNS
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="DNS Domains"><?= $each['U_DNS_DOMAINS'] ?></span>
                                    <span class="badge badge-info" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Records"><?= $each['U_DNS_RECORDS'] ?></span>
                                    <span class="badge badge-danger" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Suspended"><?= $each['SUSPENDED_DNS'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail" class="nav-link <?php if ($active[1] == 'mail') echo "active"; ?>">
                            <i class="nav-icon fas fa-envelope"></i>
                            <p>
                                Mail
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Mail Domains"><?= $each['U_MAIL_DOMAINS'] ?></span>
                                    <span class="badge badge-info" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Mail Accounts"><?= $each['U_MAIL_ACCOUNTS'] ?></span>
                                    <span class="badge badge-danger" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Suspended"><?= $each['SUSPENDED_MAIL'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db" class="nav-link <?php if ($active[1] == 'db') echo "active"; ?>">
                            <i class="nav-icon fas fa-database"></i>
                            <p>
                                Database
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Databases"><?= $each['U_DATABASES'] ?></span>
                                    <span class="badge badge-danger" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Suspended"><?= $each['SUSPENDED_DB'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/cron" class="nav-link <?php if ($active[1] == 'cron') echo "active"; ?>">
                            <i class="nav-icon fas fa-cogs"></i>
                            <p>
                                Cron Jobs
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="CRON Jobss"><?= $each['U_CRON_JOBS'] ?></span>
                                    <span class="badge badge-danger" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Suspended"><?= $each['SUSPENDED_CRON'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/back" class="nav-link <?php if ($active[1] == 'back') echo "active"; ?>">
                            <i class="nav-icon fas fa-upload"></i>
                            <p>
                                Backups
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Backups"><?= $each['U_BACKUPS'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/log" class="nav-link <?php if ($active[1] == 'log') echo "active"; ?>">
                            <i class="nav-icon fas fa-history"></i>
                            <p>
                                Logs
                                <span class="right">
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="bottom" data-html="true" title="Logs"><?= $each['U_BACKUPS'] ?></span>
                                </span>
                            </p>
                        </a>
                    </li>
                    <?php if ($_SESSION['user'] == 'admin' && empty($_SESSION['look'])) { ?>
                        <li class="nav-item has-treeview <?php if ($active[1] == 'server') echo "menu-open"; ?>">
                            <a href="#" class="nav-link <?php if ($active[1] == 'server') echo "active"; ?>">
                                <i class="nav-icon fas fa-server"></i>
                                <p>
                                    Server
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/dash" class="nav-link <?php if ($active[2] == 'dash') echo "active"; ?>">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="nav-link <?php if ($active[1] == 'server' && empty($active[2])) echo "active"; ?>">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Server Info</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/graph" class="nav-link <?php if ($active[2] == 'graph') echo "active"; ?>">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Graph</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/stats" class="nav-link <?php if ($active[1] == 'stats' && empty($active[1])) echo "active"; ?>">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Statastics</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/updates" class="nav-link <?php if ($active[2] == 'updates') echo "active"; ?>">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Updates</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            </nav>
        <?php
        }
        ?>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>