<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>" class="brand-link">
        <?= Html::img('AdminLTELogo.png', 'KumbiaPHP logo', 'class="brand-image img-circle elevation-3" style="opacity: .8"') ?>
        <!-- <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
        <span class="brand-text font-weight-light">BaseApp.Core</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">

        <?php
        include(APP_PATH . 'libs/stats.php');
        $active = explode('/', $_SERVER['REQUEST_URI']);
        ?>
        <!-- Sidebar Menu -->
        <?php
        //foreach ($result as $key => $each) {
        ?>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/') echo "active"; ?>">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            <?= $_SESSION['user']; ?>
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <!-- <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Starter Pages
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a> -->
                    <!-- <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Active Page</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link ">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Inactive Page</p>
                            </a>
                        </li>
                    </ul> -->
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/user/edit/<?php if (isset($_SESSION['look'])) {
                                                                                        echo $_SESSION['look'];
                                                                                    } else {
                                                                                        echo $_SESSION['user'];
                                                                                    } ?>" class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/myaccount/*') echo "active"; ?>">
                                <i class="fas fa-home nav-icon"></i>
                                <p>My Account</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item ">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/user" class="nav-link <?php if ($active[1] == 'user') echo "active"; ?>">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Users
                            <span class="right badge badge-danger"><? // echo $each['U_USERS']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/web" class="nav-link <?php if ($active[1] == 'web' || $active[1] == 'weblog') echo "active"; ?>">
                        <i class="nav-icon fas fa-globe"></i>
                        <p>
                            Web
                            <span class="right badge badge-danger"><? // echo $each['U_WEB_DOMAINS']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/dns" class="nav-link <?php if ($active[1] == 'dns') echo "active"; ?>">
                        <i class="nav-icon fas fa-sitemap"></i>
                        <p>
                            DNS
                            <span class="right badge badge-danger"><? // echo $each['U_DNS_RECORDS']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/mail" class="nav-link <?php if ($active[1] == 'mail') echo "active"; ?>">
                        <i class="nav-icon fas fa-envelope"></i>
                        <p>
                            Mail
                            <span class="right badge badge-danger"><? // echo $each['U_MAIL_DOMAINS']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/db" class="nav-link <?php if ($active[1] == 'db') echo "active"; ?>">
                        <i class="nav-icon fas fa-database"></i>
                        <p>
                            Database
                            <span class="right badge badge-danger"><? // echo $each['U_DATABASES']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/cron" class="nav-link <?php if ($active[1] == 'cron') echo "active"; ?>">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            Cron Jobs
                            <span class="right badge badge-danger"><? // echo $each['U_CRON_JOBS']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/back" class="nav-link <?php if ($active[1] == 'back') echo "active"; ?>">
                        <i class="nav-icon fas fa-upload"></i>
                        <p>
                            Backups
                            <span class="right badge badge-danger"><? // echo $each['U_BACKUPS']  
                                                                    ?></span>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <?php
        //   }
        ?>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>