<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?
    // echo "<pre>", print_r($data, true), "</pre>";
    ?>

    <title>Add User</title>

    <div class="col-4">
        <p class="login-box-msg"><b>Adding User</b></p>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'];
            $_SESSION['error_msg'] = NULL;
            ?>
        </p>
        <form name="v_add_user" action="https://<?= $_SERVER['HTTP_HOST'] ?>/user/add" method="post">
            <div class="input-group mb-3">
                <input type="text" name="v_username" class="form-control" placeholder="Username">
            </div>
            <div class="input-group mb-3">
                <input type="password" name="v_password" class="form-control" placeholder="Password">
            </div>
            <div class="input-group mb-3">
                <input type="text" name="v_email" class="form-control" placeholder="Email">
            </div>
            <div class="input-group mb-3">
                <select name="v_package" class="form-control">
                    <?php
                    foreach ($data as $key => $value) { ?>
                        <option value="<?= $key ?>"><?= $key; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-group mb-3">
                <input type="text" name="v_fname" class="form-control" placeholder="First Name">
            </div>
            <div class="input-group mb-3">
                <input type="text" name="v_lname" class="form-control" placeholder="Last Name">
            </div>
            <div class="input-group mb-3">
                <input type="text" name="v_notify" class="form-control" placeholder="Send login credentials to this email">
            </div>
            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

                    <button type="submit" class="btn btn-primary btn-block">Confirm</button>
                    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reset" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
        </form>
    </div>

</body>


</html>

<?php
// echo "<pre>", print_r($data);