<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>

<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/user/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add user
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Name</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="package" data-filter-control="input" data-sortable="true">Package</th>
            <th data-field="ip" data-filter-control="input" data-sortable="true">IP</th>
            <th data-field="disk" data-filter-control="input" data-sortable="true" title="Disk"><i class="fas fa-hdd"></i></th>
            <th data-field="bandwidth" data-filter-control="input" data-sortable="true" title="Bandwidth"><i class="fas fa-exchange-alt"></i></th>
            <th data-field="web" data-filter-control="input" data-sortable="true" title="Web"><i class="fas fa-globe"></i></th>
            <th data-field="mail" data-filter-control="input" data-sortable="true" title="Mail"><i class="fas fa-mail-bulk"></i></th>
            <th data-field="dns" data-filter-control="input" data-sortable="true" title="DNS"><i class="nav-icon fas fa-sitemap"></i></th>
            <th data-field="db" data-filter-control="input" data-sortable="true" title="Databases"><i class="nav-icon fas fa-database"></i></th>
            <th data-field="cron" data-filter-control="input" data-sortable="true" title="Cron"><i class="nav-icon fas fa-cogs"></i></th>
            <th data-field="backup" data-filter-control="input" data-sortable="true" title="Backup"><i class="nav-icon fas fa-upload"></i></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
                <td> <b><? echo $key ?></b><br>Email:<? echo $each['CONTACT'] ?></td>
                <td>
                    <?php if (!isset($_SESSION['look'])) { ?>
                        <a class="login" href="https://<?= $_SERVER['HTTP_HOST'] ?>/loginas/index/<?= $key ?>" title="Login">
                            <i class="fas fa-sign-in-alt status-icon green status-icon dim icon-large"></i>
                        </a>
                    <?php
                    }
                    ?>
                    <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/user/edit/<?= $key ?>" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    <?php if ($_SESSION['user'] == 'admin') {

                        if ($each['SUSPENDED'] != 'yes') { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/user/suspend/<?= $key ?>/<?= $_SESSION['token']; ?>" title="Suspend">
                                <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                            </a>
                        <?php } else { ?>
                            <a class="suspend" href="https://<?= $_SERVER['HTTP_HOST'] ?>/user/unsuspend/<?= $key ?>/<?= $_SESSION['token']; ?>" title="Unsuspend">
                                <i class="fas fa-play status-icon highlight status-icon dim do_suspend"></i>
                            </a>
                    <?php }
                    } ?>
                    <a class="remove" href="https://<?= $_SERVER['HTTP_HOST'] ?>/user/delete/<?= $key ?>/<?= $_SESSION['token']; ?>" title="Remove">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
                <td><? echo $each['PACKAGE'] ?></td>
                <td><? echo $each['IP_AVAIL'] ?></td>
                <td><? echo $each['DISK_QUOTA'] ?> MB</td>
                <td><? echo $each['U_BANDWIDTH'] ?> MB</td>
                <td><? echo $each['U_DISK_WEB'] ?></td>
                <td><? echo $each['U_DISK_MAIL'] ?></td>
                <td><? echo $each['U_DNS_DOMAINS'] ?></td>
                <td><? echo $each['U_DATABASES'] ?></td>
                <td><? echo $each['U_CRON_JOBS'] ?></td>
                <td><? echo $each['U_BACKUPS'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

</div>

<?php
echo "<pre>", print_r($data, true);
?>