<title>BaseApp.Core | Log in</title>

<p class="login-box-msg">Sign in to start your session</p>
<p class="text-danger text-center">
    <?php
    echo $_SESSION['error_msg'];
    $_SESSION['error_msg'] = NULL;
    ?>
</p>
<form action="https://<?= $_SERVER['HTTP_HOST'] ?>/login/auth" method="post">
    <div class="input-group mb-3">
        <input type="text" name="user" class="form-control" placeholder="Username">
        <div class="input-group-append">
            <div class="input-group-text">
                <span class="fas fa-user"></span>
            </div>
        </div>
    </div>
    <div class="input-group mb-3">
        <input type="password" name="password" class="form-control" placeholder="Password">
        <div class="input-group-append">
            <div class="input-group-text">
                <span class="fas fa-lock"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
        </div>
        <!-- /.col -->
        <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Login In</button>
        </div>
        <!-- /.col -->
    </div>
    <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
</form>

<p class="mb-1">
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reset">I forgot my password</a>
</p>