<?php
$value =  explode('/', $_SERVER['REQUEST_URI']);
?>
<p>
    <b> <?= strtoupper($value[4]); ?> LOGS </b>
</p>
<?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
        $_SESSION['error_msg'] = NULL;
        $_SESSION['ok_msg'] = NULL;
        ?>
    </p>
<?php } ?>

<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="log" data-filter-control="input" data-sortable="true">Logs</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>

                <td>
                    <?= htmlspecialchars(trim($each)) ?>
                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php
// echo "<pre>", print_r($data, true);
?>