<?php
if ($uri[3] == NULL) { ?>
    <div class="col-4">
        <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
                $_SESSION['error_msg'] = NULL;
                $_SESSION['ok_msg'] = NULL;
                ?>
            </p>
        <?php } ?>
        <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/" method="post">
            <label for="v_hostname">Hostname</label>
            <div class="input-group mb-3">
                <input type="text" name="v_hostname" class="form-control" placeholder="Hostname" value="<?= htmlentities(trim($v_hostname, "'")) ?>">
            </div>

            <label for="v_timezone">Timezone</label>
            <div class="input-group mb-3">
                <select name="v_timezone" class="form-control">
                    <?php
                    foreach ($v_timezones as $key => $timezone) { ?>
                        <option value="<?= $key ?>" <?php if ($key == $v_timezone) {
                                                        echo 'selected';
                                                    } ?>> <?= $timezone ?></option>
                    <?php } ?>
                </select>
            </div>

            <label for="v_language">Default Language</label>
            <div class="input-group mb-3">
                <select name="v_language" class="form-control">
                    <?php
                    foreach ($languages as $key => $language) { ?>
                        <option value="<?= $language ?>" <?php if ($language == $_SESSION['LANGUAGE']) {
                                                                echo 'selected';
                                                            } ?>><?= $language; ?></option>
                        <?= $language; ?>
                        </option>
                    <?php } ?>
                </select>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow('web');" style="color:black;">WEB</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="web" style="display: <?php if (empty($v_adv)) echo 'none'; ?>;padding-left:30px;">
                    <?php if (!empty($_SESSION['PROXY_SYSTEM'])) { ?>
                        <label for="v_proxy_system">Proxy Server / <a class="generate" href="/server/edit/<?= $_SESSION['PROXY_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_proxy_system" class="form-control" value="<?= $_SESSION['PROXY_SYSTEM'] ?>" disabled>
                        </div>
                    <?php } ?>
                    <label for="v_web_system">Web Server / <a class="generate" href="/server/edit/<?= $_SESSION['WEB_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_web_system" class="form-control" value="<?= $_SESSION['WEB_SYSTEM'] ?>" disabled>
                    </div>
                    <?php if (!empty($_SESSION['WEB_BACKEND'])) { ?>
                        <label for="v_web_backend">Backend Server / <a class="generate" href="/server/edit/<?= $_SESSION['WEB_BACKEND'] ?>/"><?= __('configure') ?></a></label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_web_backend" class="form-control" value="<?= $_SESSION['WEB_BACKEND'] ?>" disabled>
                        </div>
                        <label for="v_web_backend_pool">Backend Pool Mode / <a class="generate" href="/server/edit/<?= $_SESSION['WEB_BACKEND'] ?>/"><?= __('configure') ?></a></label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_web_backend_pool" class="form-control" value="<?= $_SESSION['WEB_BACKEND_POOL'] ?>" disabled>
                        </div>
                    <?php } ?>
                </div>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow('dns');" style="color:black;">DNS</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="dns" style="display: <?php if (empty($v_adv)) echo 'none'; ?>;padding-left:30px;">
                    <label for="v_dns_system">DNS Server / <a class="generate" href="/server/edit/<?= $_SESSION['DNS_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_dns_system" class="form-control" value="<?= $_SESSION['DNS_SYSTEM'] ?>" disabled>
                    </div>
                    <label for="v_dns_cluster">DNS Cluster</label>
                    <div class="input-group mb-3">
                        <select name="v_dns_cluster" class="form-control" disabled>
                            <option value='no'><?php print __('no'); ?></option>
                            <option value='yes' <?php if ($v_dns_cluster == 'yes') echo 'selected' ?>><?php print __('yes'); ?></option>
                        </select>
                    </div>
                    <?php if ($v_dns_cluster = 'yes') {
                        $i = 0;
                        foreach ($dns_cluster as $key => $value) {
                            $i++;
                    ?>
                            <label for="v_dns_remote_host">Host <?= '#' . $i ?> </a></label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_dns_remote_host" class="form-control" value="<?= $key ?>" disabled>
                            </div>
                    <?php }
                    } ?>
                </div>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow('mail');" style="color:black;">MAIL</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="mail" style="display: <?php if (empty($v_mail_adv)) echo 'none'; ?>;padding-left:30px;">
                    <label for="v_mail_system">MAIL Server / <a class="generate" href="/server/edit/<?= $_SESSION['MAIL_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_mail_system" class="form-control" value="<?= $_SESSION['MAIL_SYSTEM'] ?>" disabled>
                    </div>
                    <?php if (!empty($_SESSION['ANTIVIRUS_SYSTEM'])) { ?>
                        <label for="v_antivirus_system">Antivirus / <a class="generate" href="/server/edit/<?= $_SESSION['ANTIVIRUS_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_antivirus_system" class="form-control" value="<?= $_SESSION['ANTIVIRUS_SYSTEM'] ?>" disabled>
                        </div>
                    <?php } ?>
                    <?php if (!empty($_SESSION['ANTISPAM_SYSTEM'])) { ?>
                        <label for="v_antispam_system">AntiSpam / <a class="generate" href="/server/edit/<?= $_SESSION['ANTISPAM_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_antispam_system" class="form-control" value="<?= $_SESSION['ANTISPAM_SYSTEM'] ?>" disabled>
                        </div>
                    <?php } ?>
                    <label for="v_mail_url">Webmail URL </label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_mail_url" placeholder="Webmail URL" class="form-control" value="<?php echo $_SESSION['MAIL_URL']; ?>">
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow('db');" style="color:black;">DB</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="db" style="display: <?php if (empty($v_db_adv)) echo 'none'; ?>;padding-left:30px;">
                    <label for="v_mysql">MySQL Support / <a class="generate" href="/server/edit/mysql/"><?= __('configure') ?></a></label>
                    <div class="input-group mb-3">
                        <select name="v_mysql" class="form-control" disabled>
                            <option value='no'><?php print __('no'); ?></option>
                            <option value='yes' <?php if ($v_mysql == 'yes') echo 'selected' ?>><?php print __('yes'); ?></option>
                        </select>
                    </div>
                    <?php if ($v_mysql == 'yes') { ?>
                        <label for="v_mysql_url">phpMyAdmin URL</label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_mysql_url" class="form-control" placeholder="phpMyAdmin URL" value="<?= $_SESSION['DB_PMA_URL'] ?>">
                        </div>
                    <?php } ?>
                    <?php if ($v_mysql == 'yes') {
                        $i = 0;
                        foreach ($v_mysql_hosts as $value) {
                            $i++;
                    ?>
                            <label for="v_mysql_host">Host #<?= $i ?></label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_mysql_host" class="form-control" value="<?= $value['HOST'] ?>" disabled>
                            </div>
                            <label for="v_mysql_password">Password</label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_mysql_password" class="form-control" placeholder="Password">
                            </div>
                            <label for="v_mysql_max">Maximum Number Of Databases</label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_mysql_max" class="form-control" value="<?= $value['MAX_DB'] ?>" disabled>
                            </div>
                            <label for="v_mysql_max">Current Number Of Databases</label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_mysql_max" class="form-control" value="<?= $value['U_DB_BASES'] ?>" disabled>
                            </div>
                    <?php }
                    } ?>
                    <label for="v_pgsql">PostgreSQL Support / <a class="generate" href="/edit/server/postgresql/"><?= __('configure') ?></a></label>
                    <div class="input-group mb-3">
                        <select name="v_pgsql" class="form-control" disabled>
                            <option value='no'><?php print __('no'); ?></option>
                            <option value='yes' <?php if ($v_pgsql == 'yes') echo 'selected' ?>><?php print __('yes'); ?></option>
                        </select>
                    </div>
                    <?php if ($v_pgsql == 'yes') { ?>
                        <label for="v_pgsql_url">phpPgAdmin URL</label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_pgsql_url" class="form-control" value="<?= $_SESSION['DB_PGA_URL'] ?>" disabled>
                        </div>
                    <?php } ?>
                    <?php if ($v_pgsql == 'yes') {
                        $i = 0;
                        foreach ($v_pgsql_hosts as $value) {
                            $i++;
                    ?>
                            <label for="v_pgsql_host">Host #<?= $i ?> </label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_pgsql_host" class="form-control" value="<?= $value['HOST'] ?>" disabled>
                            </div>
                            <label for="v_psql_max">Maximum Number Of Databases</label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_psql_max" class="form-control" value="<?= $value['MAX_DB'] ?>" disabled>
                            </div>
                            <label for="v_pgsql_max">Current Number Of Databases</label>
                            <div class="input-group mb-3">
                                <input type="text" name="v_pgsql_max" class="form-control" value="<?= $value['U_DB_BASES'] ?>" disabled>
                            </div>
                    <?php }
                    } ?>
                </div>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow('backup');" style="color:black;">BACKUP</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="backup" style="display: <?php if (empty($v_backup_adv)) echo 'none'; ?>;padding-left:30px;">
                    <label for="v_backup">Local backup</label>
                    <div class="input-group mb-3">
                        <select name="v_backup" class="form-control">
                            <option value='no'><?php print __('no'); ?></option>
                            <option value='yes' <?php if ($v_backup == 'yes') echo 'selected' ?>><?php print __('yes'); ?></option>
                        </select>
                    </div>
                    <label for="v_backup_gzip">Compression level</a></label>
                    <div class="input-group mb-3">
                        <select name="v_backup_gzip" class="form-control">
                            <option value='1' <?php if ($v_backup_gzip == '1') echo 'selected' ?>>1</option>
                            <option value='2' <?php if ($v_backup_gzip == '2') echo 'selected' ?>>2</option>
                            <option value='3' <?php if ($v_backup_gzip == '3') echo 'selected' ?>>3</option>
                            <option value='4' <?php if ($v_backup_gzip == '4') echo 'selected' ?>>4</option>
                            <option value='5' <?php if ($v_backup_gzip == '5') echo 'selected' ?>>5</option>
                            <option value='6' <?php if ($v_backup_gzip == '6') echo 'selected' ?>>6</option>
                            <option value='7' <?php if ($v_backup_gzip == '7') echo 'selected' ?>>7</option>
                            <option value='8' <?php if ($v_backup_gzip == '8') echo 'selected' ?>>8</option>
                            <option value='9' <?php if ($v_backup_gzip == '9') echo 'selected' ?>>9</option>
                        </select>
                    </div>
                    <label for="v_backup_dir">Directory</label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_backup_dir" class="form-control" value="<?= trim($v_backup_dir, "'") ?>">
                    </div>
                    <b><a href="javascript:elementHideShow('remote_backup');" style="color:black;">Remote backup</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                    <div class="mt-2" id="remote_backup" style="display: <?php if (empty($v_backup_remote_adv)) echo 'none'; ?>;padding-left:30px;">
                        <label for="v_backup_type">Protocol</label>
                        <div class="input-group mb-3">
                            <select name="v_backup_type" class="form-control">
                                <option value='ftp'><?php print __('ftp'); ?></option>
                                <option value='sftp' <?php if ((!empty($v_backup_type)) && ($v_backup_type  == 'sftp')) echo 'selected' ?>><?php print __('sftp'); ?></option>
                            </select>
                        </div>
                        <label for="v_backup_host">Host</label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_backup_host" class="form-control" value="<?trim($v_backup_host, "'")?>">
                        </div>
                        <label for="v_backup_username">Username</label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_backup_username" class="form-control" value="<?trim($v_backup_username, "'")?>">
                        </div>
                        <label for="v_backup_password">Password</label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_backup_password" class="form-control" value="<?trim($v_backup_password, "'")?>">
                        </div>
                        <label for="v_backup_bpath">Directory</label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_backup_bpath" class="form-control" value="<?trim($v_backup_bpath, "'")?>">
                        </div>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow(' ssl');" style="color:black;">VESTA SSL</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="ssl" style="display: <?php if (empty($v_adv)) echo 'none'; ?>;padding-left:30px;">
                    <div class="input-group form-control mb-3">
                        <input type="checkbox" name="v_web_ssl_domain_checkbox" onclick="javascript:elementHideShow('domain_ssl');">
                        <label for="v_web_ssl_domain_checkbox"> &nbsp; Use Web Domain SSL Certificate</label>
                        <div class="mt-2" id="domain_ssl" style="display: <?php if (empty($v_adv)) echo 'none'; ?>;padding-left:30px;">
                            <select name="v_web_ssl_domain" class="form-control">
                                <option value='' <?php if (empty($_SESSION['VESTA_CERTIFICATE'])) echo 'selected' ?>></option>
                                <?php foreach ($v_ssl_domains as $key => $value) { ?>
                                    <option value="<?= $value ?>" <?php if ((!empty($_SESSION['VESTA_CERTIFICATE'])) && ($value == $_SESSION['VESTA_CERTIFICATE'])) {
                                                                    ?> selected <?php } ?> <?php if ((!empty($_SESSION['VESTA_CERTIFICATE'])) && ($value == $_POST['v_vesta_certificate'])) { ?> selected <?php } ?>><?= $value ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <label for="v_hostname">Web Server/ Cofigure</label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_hostname" class="form-control" placeholder="Hostname" value="<?= htmlentities(trim($v_hostname, "'")) ?>">
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <b><a href="javascript:elementHideShow('vesta');" style="color:black;">VESTA Control Panel Plugins</a></b>&nbsp;<i class="fas fa-sort-down"></i>
                <div class="mt-2" id="vesta" style="display: <?php if (empty($v_adv)) echo 'none'; ?>;padding-left:30px;">
                    <?php if (!empty($_SESSION['PROXY_SYSTEM'])) { ?>
                        <label for="v_hostname">Proxy Server / <a class="generate" href="/server/edit/<? echo $_SESSION['PROXY_SYSTEM'] ?>/"><?= __('configure') ?></a></label>
                        <div class="input-group mb-3">
                            <input type="text" name="v_hostname" class="form-control" placeholder="Hostname" value="<?= htmlentities(trim($v_hostname, "'")) ?>">
                        </div>
                    <?php } ?>
                    <label for="v_hostname">Web Server/ Cofigure</label>
                    <div class="input-group mb-3">
                        <input type="text" name="v_hostname" class="form-control" placeholder="Hostname" value="<?= htmlentities(trim($v_hostname, "'")) ?>">
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </form>
    </div>
<?php
} ?>

<?php
if ($uri[3] == 'apache2' || $uri[3] == 'httpd') { ?>
    <div class="col-8">
        <p class="login-box-msg"><b>Configuring Server <?= strtoupper($v_service_name) ?></b></p>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/php">Configure php.ini</a>
        <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
                $_SESSION['error_msg'] = NULL;
                $_SESSION['ok_msg'] = NULL;
                ?>
            </p>
        <?php } ?>

        <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= strtolower($v_service_name) ?>" method="post">
            <label for="v_config"><?= $v_config_path ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
            </div>

            <div class="col-4 input-group form-control mb-3">
                <input type="checkbox" name="v_restart" checked=yes>
                <label for="v_restart"> &nbsp; Restart </label>
            </div>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </form>
    </div>
<?php
} ?>

<?php if ($uri[3] == 'bind9') { ?>
    <div class="col-8">
        <p class="login-box-msg"><b>Configuring Server <?= strtoupper($v_service_name) ?></b></p>
        <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
                $_SESSION['error_msg'] = NULL;
                $_SESSION['ok_msg'] = NULL;
                ?>
            </p>
        <?php } ?>
        <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= strtolower($v_service_name) ?>" method="post">

            <label for="v_config"><?= $v_options_path ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config" class="form-control" rows="15"><?= $v_options ?></textarea>
            </div>

            <label for="v_config"><?= $v_config_path ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
            </div>

            <div class="col-4 input-group form-control mb-3">
                <input type="checkbox" name="v_restart" checked=yes>
                <label for="v_restart"> &nbsp; Restart </label>
            </div>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </form>
    </div>
<?php
} ?>

<?php if ($uri[3] == 'dovecot') { ?>
    <div class="col-8">
        <p class="login-box-msg"><b>Configuring Server <?= strtoupper($v_service_name) ?></b></p>
        <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
                $_SESSION['error_msg'] = NULL;
                $_SESSION['ok_msg'] = NULL;
                ?>
            </p>
        <?php } ?>

        <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= $v_service_name ?>" method="post">

            <label for="v_config"><?= $v_config_path ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config" class="form-control" rows="8"><?= $v_config ?></textarea>
            </div>

            <label for="v_config1"><?= $v_config_path1 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config1" class="form-control" rows="8"><?= $v_config1 ?></textarea>
            </div>

            <label for="v_config2"><?= $v_config_path2 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config2" class="form-control" rows="8"><?= $v_config2 ?></textarea>
            </div>

            <label for="v_config3"><?= $v_config_path3 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config3" class="form-control" rows="8"><?= $v_config3 ?></textarea>
            </div>

            <label for="v_config4"><?= $v_config_path4 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config4" class="form-control" rows="8"><?= $v_config4 ?></textarea>
            </div>

            <label for="v_config5"><?= $v_config_path5 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config5" class="form-control" rows="8"><?= $v_config5 ?></textarea>
            </div>

            <label for="v_config6"><?= $v_config_path6 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config6" class="form-control" rows="8"><?= $v_config6 ?></textarea>
            </div>

            <label for="v_config7"><?= $v_config_path7 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config7" class="form-control" rows="8"><?= $v_config7 ?></textarea>
            </div>

            <label for="v_config8"><?= $v_config_path8 ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config8" class="form-control" rows="8"><?= $v_config8 ?></textarea>
            </div>

            <div class="col-4 input-group form-control mb-3">
                <input type="checkbox" name="v_restart" checked=yes>
                <label for="v_restart"> &nbsp; Restart </label>
            </div>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </form>
    </div>
<?php
} ?>

<?php if ($uri[3] == 'iptables') { ?>
    Check
<?php
} ?>


<?php if ($uri[3] == 'mysql' || $uri[3] == 'mariadb' || $uri[3] == 'mysqld') { ?>
    <p class="login-box-msg"><b>Configuring Server <?= strtoupper($v_service_name) ?></b></p>
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>

    <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= strtolower($v_service_name) ?>" method="post">

        <div class="col-4">
            <div id="basic-options">
                <label for="v_max_connections">max_connections</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_max_connections" class="form-control" regexp="max_connections" prev_value="<?= htmlentities($v_max_connections) ?>" value="<?= htmlentities($v_max_connections) ?>">
                </div>

                <label for="v_max_user_connections">max_user_connections</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_max_user_connections" class="form-control" regexp="max_user_connections" prev_value="<?= htmlentities($v_max_user_connections) ?>" value="<?= htmlentities($v_max_user_connections) ?>">
                </div>

                <label for="v_wait_timeout">wait_timeout</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_wait_timeout" class="form-control" regexp="wait_timeout" prev_value="<?= htmlentities($v_wait_timeout) ?>" value="<?= htmlentities($v_wait_timeout) ?>">
                </div>

                <label for="v_interactive_timeout">interactive_timeout</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_interactive_timeout" class="form-control" regexp="interactive_timeout" prev_value="<?= htmlentities($v_interactive_timeout) ?>" value="<?= htmlentities($v_interactive_timeout) ?>">
                </div>

                <label for="v_max_allowed_packet">max_allowed_packet</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_max_allowed_packet" class="form-control" regexp="max_allowed_packet" prev_value="<?= htmlentities($v_max_allowed_packet) ?>" value="<?= htmlentities($v_max_allowed_packet) ?>">
                </div>

                <a href="javascript:toggleOptions();"> <?= strtoupper('Advanced Options') ?></a>

            </div>
        </div>

        <div class="col-8">
            <div id="advanced-options" style="display:<?php if (empty($v_adv)) echo 'none'; ?> ;">
                <a href="javascript:toggleOptions();"> <?= strtoupper('Basic Options') ?></a>
                <br>

                <label for="v_config"><?= $v_config_path ?></label>
                <div class="input-group mb-3">
                    <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
                </div>

                <div class="input-group form-control mb-3">
                    <input type="checkbox" name="v_restart" checked=yes>
                    <label for="v_restart"> &nbsp; Restart </label>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- /.col -->

            <!-- /.col -->
        </div>

        <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </div>
    </form>
<?php
} ?>

<?php if ($uri[3] == 'nginx') { ?>
    <p class="login-box-msg"><b>Configuring Server <?= strtoupper($uri[3]) ?></b></p>
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>
    <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<? strtolower($uri[3]) ?>" method="post">

        <div class="col-4">
            <div id="basic-options">
                <label for="v_worker_processes">worker_processes</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_worker_processes" class="form-control" regexp="worker_processes" prev_value="<?= htmlentities($v_worker_processes) ?>" value="<?= htmlentities($v_worker_processes) ?>">
                </div>

                <label for="v_worker_connections">worker_connections</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_worker_connections" class="form-control" regexp="worker_connections" prev_value="<?= htmlentities($v_worker_connections) ?>" value="<?= htmlentities($v_worker_connections) ?>">
                </div>

                <label for="v_client_max_body_size">client_max_body_size</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_client_max_body_size" class="form-control" regexp="client_max_body_size" prev_value="<?= htmlentities($v_client_max_body_size) ?>" value="<?= htmlentities($v_client_max_body_size) ?>">
                </div>

                <label for="v_send_timeout">send_timeout</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_send_timeout" class="form-control" regexp="send_timeout" prev_value="<?= htmlentities($v_send_timeout) ?>" value="<?= htmlentities($v_send_timeout) ?>">
                </div>

                <label for="v_proxy_connect_timeout">proxy_connect_timeout</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_proxy_connect_timeout" class="form-control" regexp="proxy_connect_timeout" prev_value="<?= htmlentities($v_proxy_connect_timeout) ?>" value="<?= htmlentities($v_proxy_connect_timeout) ?>">
                </div>

                <label for="v_proxy_send_timeout">proxy_send_timeout</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_proxy_send_timeout" class="form-control" regexp="proxy_send_timeout" prev_value="<?= htmlentities($v_proxy_send_timeout) ?>" value="<?= htmlentities($v_proxy_send_timeout) ?>">
                </div>

                <label for="v_proxy_read_timeout">proxy_read_timeout</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_proxy_read_timeout" class="form-control" regexp="proxy_read_timeout" prev_value="<?= htmlentities($v_proxy_read_timeout) ?>" value="<?= htmlentities($v_proxy_read_timeout) ?>">
                </div>

                <label for="v_gzip">gzip</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_gzip" class="form-control" regexp="gzip" prev_value="<?= htmlentities($v_gzip) ?>" value="<?= htmlentities($v_gzip) ?>">
                </div>

                <label for="v_gzip_comp_level">gzip_comp_level</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_gzip_comp_level" class="form-control" regexp="gzip_comp_level" prev_value="<?= htmlentities($v_gzip_comp_level) ?>" value="<?= htmlentities($v_gzip_comp_level) ?>">
                </div>

                <label for="v_charset">charset</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_charset" class="form-control" regexp="charset" prev_value="<?= htmlentities($v_charset) ?>" value="<?= htmlentities($v_charset) ?>">
                </div>

                <a href="javascript:toggleOptions();"> <?= strtoupper('Advanced Options') ?></a>

            </div>
        </div>

        <div class="col-8">
            <div id="advanced-options" style="display:<?php if (empty($v_adv)) echo 'none'; ?> ;">
                <a href="javascript:toggleOptions();"> <?= strtoupper('Basic Options') ?></a>
                <br>
                <label for="v_config"><?= $v_config_path ?></label>
                <div class="input-group mb-3">
                    <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
                </div>

                <div class="input-group form-control mb-3">
                    <input type="checkbox" name="v_restart" checked=yes>
                    <label for="v_restart"> &nbsp; Restart </label>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- /.col -->

            <!-- /.col -->
        </div>

        <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </div>
    </form>
<?php
} ?>


<?php if ($uri[3] == 'php' || $uri[3] == 'php-fpm' || $uri[3] == 'php5-fpm') { ?>
    <p class="login-box-msg"><b>Configuring Server <?= strtoupper($uri[3]) ?></b></p>
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>
    <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= $uri[3] ?>" method="post">

        <div class="col-4">
            <div id="basic-options">
                <label for="v_max_execution_time">max_execution_time</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_max_execution_time" class="form-control" regexp="max_execution_time" prev_value="<?= htmlentities($v_max_execution_time) ?>" value="<?= htmlentities($v_max_execution_time) ?>">
                </div>

                <label for="v_max_input_time">max_input_time</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_max_input_time" class="form-control" regexp="max_input_time" prev_value="<?= htmlentities($v_max_input_time) ?>" value="<?= htmlentities($v_max_input_time) ?>">
                </div>

                <label for="v_memory_limit">memory_limit</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_memory_limit" class="form-control" regexp="memory_limit" prev_value="<?= htmlentities($v_memory_limit) ?>" value="<?= htmlentities($v_memory_limit) ?>">
                </div>

                <label for="v_error_reporting">error_reporting</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_error_reporting" class="form-control" regexp="error_reporting" prev_value="<?= htmlentities($v_error_reporting) ?>" value="<?= htmlentities($v_error_reporting) ?>">
                </div>

                <label for="v_display_errors">display_errors</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_display_errors" class="form-control" regexp="display_errors" prev_value="<?= htmlentities($v_display_errors) ?>" value="<?= htmlentities($v_display_errors) ?>">
                </div>

                <label for="v_post_max_size">post_max_size</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_post_max_size" class="form-control" regexp="post_max_size" prev_value="<?= htmlentities($v_post_max_size) ?>" value="<?= htmlentities($v_post_max_size) ?>">
                </div>

                <label for="v_upload_max_filesize">upload_max_filesize</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_upload_max_filesize" class="form-control" regexp="upload_max_filesize" prev_value="<?= htmlentities($v_upload_max_filesize) ?>" value="<?= htmlentities($v_upload_max_filesize) ?>">
                </div>

                <a href="javascript:toggleOptions();"> <?= strtoupper('Advanced Options') ?></a>

            </div>
        </div>

        <div class="col-8">
            <div id="advanced-options" style="display:<?php if (empty($v_adv)) echo 'none'; ?> ;">
                <a href="javascript:toggleOptions();"> <?= strtoupper('Basic Options') ?></a>
                <br>

                <label for="v_config"><?= $v_config_path ?></label>
                <div class="input-group mb-3">
                    <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
                </div>

                <div class="input-group form-control mb-3">
                    <input type="checkbox" name="v_restart" checked=yes>
                    <label for="v_restart"> &nbsp; Restart </label>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- /.col -->

            <!-- /.col -->
        </div>

        <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </div>
    </form>

<?php
} ?>

<?php if ($uri[3] == 'postgresql') { ?>

<?php
} ?>

<?php if ($uri[3] == 'spamassassin') { ?>
    <div class="col-8">
        <p class="login-box-msg"><b>Configuring Server <?= strtoupper($v_service_name) ?></b></p>
        <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
                $_SESSION['error_msg'] = NULL;
                $_SESSION['ok_msg'] = NULL;
                ?>
            </p>
        <?php } ?>

        <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= strtolower($v_service_name) ?>" method="post">

            <label for="v_config"><?= $v_config_path ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
            </div>

            <div class="col-4 input-group form-control mb-3">
                <input type="checkbox" name="v_restart" checked=yes>
                <label for="v_restart"> &nbsp; Restart </label>
            </div>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </form>
    </div>
<?php
} ?>

<?php if ($uri[3] == 'vsftpd' || $uri[3] == 'cron' || $uri[3] == 'clamd' || $uri[3] == 'crond' || $uri[3] == 'exim' || $uri[3] == 'exim4' || $uri[3] == 'fail2ban' || $uri[3] == 'named' || $uri[3] == 'proftpd' || $uri[3] == 'spamd') { ?>
    <div class="col-8">
        <p class="login-box-msg"><b>Configuring Server <?= strtoupper($v_service_name) ?></b></p>
        <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
            <p class="text-center">
                <?php
                echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
                $_SESSION['error_msg'] = NULL;
                $_SESSION['ok_msg'] = NULL;
                ?>
            </p>
        <?php } ?>
        <form name="v_configure_server" action="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= strtolower($v_service_name) ?>" method="post">

            <label for="v_config"><?= $v_config_path ?></label>
            <div class="input-group mb-3">
                <textarea name="v_config" class="form-control" rows="15"><?= $v_config ?></textarea>
            </div>

            <div class="col-4 input-group form-control mb-3">
                <input type="checkbox" name="v_restart" checked=yes>
                <label for="v_restart"> &nbsp; Restart </label>
            </div>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" class="btn btn-default btn-block">Back</a>
            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">
        </form>
    </div>
<?php
} ?>