<?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
        $_SESSION['error_msg'] = NULL;
        $_SESSION['ok_msg'] = NULL;
        ?>
    </p>
<?php } ?>
<div id="toolbar">
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="action" data-filter-control="input" data-sortable="true">Date</th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Name</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td>
                    <?= translate_date($each['DATE']) ?>
                    <br>
                    <br>
                    <?= $each['TIME'] ?>
                </td>
                <td>
                    <b><? echo $each['TITLE'] ?></b>
                    <br>
                    <p><img src="https://<?= $_SERVER['HTTP_HOST'] ?>/server/graphimage/<?= $each['TYPE'] . "/" . "daily" . "-" . $each['RRD'] ?>"></p>
                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>