<?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
        $_SESSION['error_msg'] = NULL;
        $_SESSION['ok_msg'] = NULL;
        ?>
    </p>
<?php } ?>
<div id="toolbar">
</div>
<ul class="nav nav-tabs" id="custom-content-above-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="daily-home-tab" data-toggle="pill" href="#daily-home" role="tab" aria-controls="custom-content-above-home" aria-selected="true">Daily</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="weekly-tab" data-toggle="pill" href="#weekly" role="tab" aria-controls="weekly" aria-selected="false">Weekly</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="monthly-tab" data-toggle="pill" href="#monthly" role="tab" aria-controls="monthly" aria-selected="false">Monthly</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="yearly-tab" data-toggle="pill" href="#yearly" role="tab" aria-controls="yearly" aria-selected="false">Yearly</a>
    </li>
</ul>
<!-- <table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="false" data-show-refresh="false" data-show-toggle="false" data-show-fullscreen="false" data-show-columns="false" data-show-columns-toggle-all="false" data-show-export="false" data-click-to-select="false" data-minimum-count-columns="2" data-id-field="name" " data-show-footer="false" data-show-export="false" data-response-handler="responseHandler"> -->
<table class="table table-condensed tab-custom-content">
    <thead>
        <tr>
            <th data-field="action" data-filter-control="input" data-sortable="false">Date</th>
            <th data-field="name" data-filter-control="input" data-sortable="false">Name</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td>
                    <?= translate_date($each['DATE']) ?>
                    <br>
                    <br>
                    <?= $each['TIME'] ?>
                </td>
                <td>
                    <b><? echo $each['TITLE'] ?></b>
                    <br>
                    <p><img src="https://<?= $_SERVER['HTTP_HOST'] ?>/server/graphimage/<?= $each['TYPE'] . "/" . "daily" . "-" . $each['RRD'] ?>"></p>
                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>