<p class="text-center">
    <?php
    echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
    $_SESSION['error_msg'] = NULL;
    $_SESSION['ok_msg'] = NULL;
    ?>
</p>

<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>

    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server" id="add" class="btn btn-primary">
        <i class="fas fa-cog"></i> Configure
    </a>&emsp;
    </a>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/cpu" id="show_stat" class="btn btn-info" target="_blank">
        <i class="fas fa-info"></i>&emsp; SHOW CPU / MEM / NET / DISK
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td>
                <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/" title="Configure">
                    <i class="fas fa-cog status-icon orange status-icon dim"></i>
                </a>
                &nbsp;

                <a href="" data-toggle="modal" data-target="#exampleModalLong" title="Restart">
                    <i class="fas fa-redo-alt status-icon orange status-icon dim"></i>
                </a>

                <!-- Modal -->
                <div class="modal danger" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <span style="color: red"><b><i>The system is going down for reboot NOW!</i></b></span>
                                <br>
                                Are you sure want to restart <b><?= $sys['sysinfo']['HOSTNAME'] ?></b> .
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/system/restart/<?= $sys['sysinfo']['HOSTNAME'] ?>/<?= $_SESSION['token'] ?>" title="Restart">
                                    Yes, Restart
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                <b><?= $sys['sysinfo']['HOSTNAME'] ?></b>
                <br>
                <p><b><?= $sys['sysinfo']['OS'] ?></b> &emsp; (<?= __($sys['sysinfo']['ARCH']) ?>) &emsp; Load Average : <?= $sys['sysinfo']['LOADAVERAGE'] ?> &emsp;Uptime : <?= humanize_time($sys['sysinfo']['UPTIME']) ?></p>
            </td>
        </tr>

        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td></td>
                <td>
                    <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/edit/<?= $key ?>" title="Configure">
                        <i class="fas fa-cog status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <?php
                    if ($each['STATE'] == 'running') {
                    ?>
                        <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/service/stop/<?= $key ?>" title="Stop">
                            <i class="fas fa-stop status-icon orange status-icon dim"></i>
                        </a>&nbsp;
                    <?php
                    }
                    if ($each['STATE'] == 'stopped') { ?>
                        <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/service/start/<?= $key ?>" title="Stop">
                            <i class="fas fa-play status-icon orange status-icon dim"></i>
                        </a>&nbsp;
                    <?php
                    }
                    ?>


                    <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/service/restart/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Restart">
                        <i class="fas fa-redo-alt status-icon orange status-icon dim"></i>
                    </a>

                </td>
                <td>
                    <b><? echo $key ?></b>
                    <br>
                    <p><?= $each['SYSTEM'] ?> &emsp; CPU : <?= $each['CPU'] ?> &emsp; Memory : <?= $each['MEM'] ?> mb &emsp; Uptime: <?= humanize_time($each['RTIME']) ?></p>
                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php
// echo "<pre>", print_r($data, true);
?>