<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>
<nav class="header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/cpu" class="nav-link <?php if ($uri['3'] == 'cpu') echo "active"; ?>">CPU</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/mem" class="nav-link <?php if ($uri['3'] == 'mem') echo "active"; ?>">MEMORY</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/disk" class="nav-link <?php if ($uri['3'] == 'disk') echo "active"; ?>">DISK</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/net" class="nav-link <?php if ($uri['3'] == 'net') echo "active"; ?>">NETWORK</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/web" class="nav-link <?php if ($uri['3'] == 'web') echo "active"; ?>">WEB</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/dns" class="nav-link <?php if ($uri['3'] == 'dns') echo "active"; ?>">DNS</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/mail" class="nav-link <?php if ($uri['3'] == 'mail') echo "active"; ?>">MAIL</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/server/info/db" class="nav-link <?php if ($uri['3'] == 'db') echo "active"; ?>">DB</a>
        </li>
    </ul>
</nav>
<hr>

<?php
foreach ($data as $file) {
    echo "<pre>", $file . "\n", "</pre>";
}
?>