<?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
    <p class="text-center">
        <?php
        echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
        $_SESSION['error_msg'] = NULL;
        $_SESSION['ok_msg'] = NULL;
        ?>
    </p>
<?php } ?>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <?php if ($_SESSION['user'] == 'admin' && empty($_SESSION['look'])) { ?>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/packages/add" id="add" class="btn btn-primary">
            <i class="fas fa-plus-circle status-icon"></i> Add Package
        </a>
    <?php } ?>

</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Name</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="info" data-filter-control="input" data-sortable="true">Info</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $index = 0;
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td></td>
                <td>
                    <b><? echo $key ?></b>
                </td>
                <td>
                    <a class="edit" href="https://<?= $_SERVER['HTTP_HOST'] ?>/packages/edit/<?= $key ?>" title="Edit">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    &nbsp;
                    <a href="" data-toggle="modal" data-target="#Modal<?= $index ?>" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div class="modal danger" id="Modal<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="Modal<?= $index ?>Title" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="Modal<?= $index ?>Title">Confirmation</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure want to delete package <b><?= $key ?></b> ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="https://<?= $_SERVER['HTTP_HOST'] ?>/packages/delete/<?= $key ?>/<?= $_SESSION['token']; ?>" title="Delete">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <h3 class="card-title"><? echo $key ?></h3>
                    <br>
                    <div class="table-responsive">
                        <table style="width:100%;border:none;">
                            <tbody>
                                <tr>
                                    <th>Web - Template</th>
                                    <td><?= $each['WEB_TEMPLATE'] ?></td>
                                    <th>DNS Domain</th>
                                    <td><?= $each['DNS_DOMAINS'] ?></td>
                                    <th>Backups</th>
                                    <td><?= $each['BACKUPS'] ?></td>
                                </tr>
                                <tr>
                                    <th></th>
                                    <td></td>
                                    <th>DNS Records</th>
                                    <td><?= $each['DNS_RECORDS'] ?></td>
                                    <th>Bandwidth</th>
                                    <td><?= $each['BANDWIDTH'] ?></td>
                                </tr>
                                <tr>
                                    <th>DNS - Template</th>
                                    <td><?= $each['DNS_TEMPLATE'] ?></td>
                                    <th>Mail - Domains</th>
                                    <td><?= $each['MAIL_DOMAINS'] ?></td>
                                    <th>Disk</th>
                                    <td><?= $each['DISK_QUOTA'] ?></td>
                                </tr>
                                <tr>
                                    <th>SSH - Access</th>
                                    <td><?= $each['SHELL'] ?></td>
                                    <th>Mail - Accounts</th>
                                    <td><?= $each['MAIL_ACCOUNTS'] ?></td>
                                    <th>Name Servers</th>
                                    <td><?= $each['NS'] ?></td>
                                </tr>
                                <tr>
                                    <th>Web - Domains</th>
                                    <td><?= $each['WEB_DOMAINS'] ?></td>
                                    <th>Databases</th>
                                    <td><?= $each['DATABASES'] ?></td>
                                    <th></th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th>Web - Aliases</th>
                                    <td><?= $each['WEB_ALIASES'] ?></td>
                                    <th>Cron Jobs</th>
                                    <td><?= $each['CRON_JOBS'] ?></td>
                                    <th></th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </td>
            </tr>
        <?php
            $index++;
        }
        ?>
    </tbody>
</table>

<?php
// echo "<pre>", print_r($data, true);
?>