<div class="col-4">
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>
    <form name="v_add_web" action="https://<?= $_SERVER['HTTP_HOST'] ?>/web/addweb" method="post">
        <label for="v_domain">Domain</label> <span style="color:red">*</span>
        <div class="input-group mb-3">
            <input type="text" name="v_domain" class="form-control" placeholder="Domain" required>
        </div>
        <label for="v_ip">IP Address</label>
        <div class="input-group mb-3">
            <select name="v_ip" class="form-control">
                <?php foreach ($ips as $ip => $value) { ?>
                    <option value="<?= $value['NAT'] ?>"><?= $value['NAT']  ?></option>
                <?php } ?>

            </select>
        </div>
        <div class="input-group form-control mb-3">
            <input type="checkbox" name="v_dns" id="dns" checked=yes>
            <label class="" for="dns"> &nbsp; DNS Support</label>
        </div>

        <div class="input-group form-control mb-3">
            <input type="checkbox" name="v_mail" id="mail" checked=yes>
            <label for="mail"> &nbsp; Mail Support</label>
        </div>

        <div class="input-group mb-3">
            <b><u><a href="javascript:elementHideShow('advtable');" style="text-decoration: none;color : #000;">Advanced options</a></u></b>
        </div>

        <table class="data-col2" width="600px" style="display:<?php if (empty($v_adv)) echo 'none'; ?> ;" id="advtable">
            <tr>
                <td class="vst-text input-label">
                    <?php print __('Aliases'); ?>
                </td>
            </tr>
            <tr>
                <td>
                    <textarea size="20" class="input-group form-control" name="v_aliases" id="v_aliases"><?= htmlentities(trim($v_aliases, "'")) ?></textarea>
                </td>
            </tr>
            <?php if (!empty($_SESSION['PROXY_SYSTEM'])) {
                echo ""; ?>
                <tr>
                    <td class="vst-text step-top">
                        <label><input type="checkbox" size="20" class="vst-checkbox" name="v_proxy" <?php if ($v_proxy !== 'off') echo "checked=yes" ?> onclick="javascript:elementHideShow('proxytable');">
                            <?php print __('Proxy Support'); ?></label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table style="display:<?php if ($v_proxy == 'off') {
                                                    echo 'none';
                                                } else {
                                                    echo 'block';
                                                } ?>;" id="proxytable">
                            <tr>
                                <td class="vst-text input-label step-left">
                                    <?php print __('Proxy Extensions'); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="step-left">
                                    <textarea size="20" class="vst-textinput" name="v_proxy_ext">
                                        <?php if (!empty($v_proxy_ext)) {
                                            echo htmlentities(trim($v_proxy_ext, "'"));
                                        } else {
                                            echo 'jpeg, jpg, png, gif, bmp, ico, svg, tif, tiff, css, js, htm, html, ttf, otf, webp, woff, txt, csv, rtf, doc, docx, xls, xlsx, ppt, pptx, odf, odp, ods, odt, pdf, psd, ai, eot, eps, ps, zip, tar, tgz, gz, rar, bz2, 7z, aac, m4a, mp3, mp4, ogg, wav, wma, 3gp, avi, flv, m4v, mkv, mov, mp4, mpeg, mpg, wmv, exe, iso, dmg, swf';
                                        }  ?></textarea>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            <?php echo "";
            } ?>
            <tr>
                <td class="step-top vst-text">
                    <label><input type="checkbox" size="20" class="vst-checkbox" name="v_ssl" <?php if ($v_ssl == 'yes' || $v_ssl == 'on') echo "checked=yes" ?> onclick="javascript:elementHideShow('ssltable');">
                        <?php print __('SSL Support'); ?></label>
                </td>
            </tr>
            <tr>
                <td>
                    <table style="display:<?php if (empty($v_ssl)) {
                                                echo 'none';
                                            } else {
                                                echo 'block';
                                            } ?>;" id="ssltable">
                        <tr>
                            <td class="step-left input-label vst-text">
                                <label><input type="checkbox" size="20" class="vst-checkbox" name="v_letsencrypt" <?php if ($v_letsencrypt == 'yes' || $v_letsencrypt == 'on') echo "checked=yes" ?> onclick="App.Actions.WEB.toggle_letsencrypt(this)">
                                    <?php print __('Lets Encrypt Support'); ?></label>
                            </td>
                        </tr>
                        <tr>
                            <td class="vst-text input-label lets-encrypt-note step-left">
                                <?= __('Your certificate will be automatically issued in 5 minutes') ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="vst-text input-label step-left">
                                <?php print __('SSL Home Directory'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="step-left">
                                <select class="vst-list" name="v_ssl_home">
                                    <option value='same' <?php if ($v_ssl_home == 'same') echo "selected"; ?>>
                                        public_html
                                    </option>
                                    <option value='single' <?php if ($v_ssl_home == 'single') echo "selected"; ?>>
                                        public_shtml
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="vst-text input-label step-left">
                                <?php print __('SSL Certificate'); ?>
                                <span id="generate-csr"> / <a class="generate" target="_blank" href="/generate/ssl/?domain=<?= htmlentities(trim($v_domain, "'")) ?>"><?php print __('Generate CSR') ?></a></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="step-left">
                                <textarea size="20" class="vst-textinput" name="v_ssl_crt"><?= htmlentities(trim($v_ssl_crt, "'")) ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td class="vst-text input-label step-left">
                                <?php print __('SSL Key'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="step-left">
                                <textarea size="20" class="vst-textinput" name="v_ssl_key"><?= htmlentities(trim($v_ssl_key, "'")) ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td class="vst-text input-label step-left">
                                <?php print __('SSL Certificate Authority / Intermediate'); ?> <span class="optional">(<?php print __('optional'); ?>)</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="step-left">
                                <textarea size="20" class="vst-textinput" name="v_ssl_ca"><?= htmlentities(trim($v_ssl_ca, "'")) ?></textarea>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td class="vst-text step-top">
                    <?php print __('Web Statistics'); ?>
                </td>
            </tr>
            <tr>
                <td>
                    <select class="vst-list" name="v_stats">
                        <?php
                        foreach ($stats as $key => $value) {
                            $svalue = "'" . $value . "'";
                            echo "\t\t\t\t<option value=\"" . htmlentities($value) . "\"";
                            if (empty($v_stats)) $v_stats = 'none';
                            if (($value == $v_stats) || ($svalue == $v_stats)) {
                                echo ' selected';
                            }
                            echo ">" . htmlentities(__($value)) . "</option>\n";
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr class="stats-auth" style="<? if (trim($v_stats, "'") == ' none') { ?>display:none<? } ?>">
                <td class="step-left vst-text input-label">
                    <label><input type="checkbox" size="20" class="vst-checkbox" name="v_stats_auth" <?php if (!empty($v_stats_user)) echo "checked=yes" ?> onclick="javascript:elementHideShow('statstable');">
                        <?= __('Statistics Authorization') ?></label>
                </td>
            </tr>
            <tr>
                <td class="step-left">
                    <table style="display:<?php if (empty($v_stats_user)) {
                                                echo 'none';
                                            } else {
                                                echo 'block';
                                            } ?> ;" id="statstable" name="v-add-web-domain-stats-user">
                        <tr>
                            <td class="vst-text input-label">
                                <?php print __('Username'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="text" size="20" class="vst-input" name="v_stats_user" value="<?= htmlentities(trim($v_stats_user, "'")) ?>">
                            </td>
                        </tr>
                        <tr>
                            <td class="vst-text input-label">
                                <?php print __('Password'); ?> / <a href="javascript:WEBrandom();" class="generate"><?php print __('generate'); ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="text" size="20" class="vst-input password" name="v_stats_password" value="<?= htmlentities(trim($v_stats_password, "'")) ?>" id="v_password">
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td class="vst-text step-top">
                    <label><input type="checkbox" size="20" class="vst-checkbox" name="v_ftp" <?php if (!empty($v_ftp) && count($v_ftp_users)) echo "checked=yes" ?> onclick="App.Actions.WEB.toggle_additional_ftp_accounts(this)">
                        <?php print __('Additional FTP Account'); ?></label>
                </td>
            </tr>
            <tr>
                <td>
                    <?php foreach ($v_ftp_users as $i => $ftp_user) : ?>
                        <?php
                        $v_ftp_user     = $ftp_user['v_ftp_user'];
                        $v_ftp_password = $ftp_user['v_ftp_password'];
                        $v_ftp_path     = $ftp_user['v_ftp_path'];
                        $v_ftp_email    = $ftp_user['v_ftp_email'];
                        $v_ftp_pre_path = $ftp_user['v_ftp_pre_path'];
                        ?>
                        <table <?php echo (!empty($v_ftp)) ? "style='display: block'" : "style='display:none;'"  ?> class="ftptable ftptable-nrm" name="v_add_domain_ftp">
                            <tr>
                                <td class="vst-text input-label">
                                    <?php print __('FTP') ?> #<span class="ftp-user-number"><?php print $i + 1; ?></span> <a class="ftp-remove-user additional-control do_delete" onCLick="App.Actions.WEB.remove_ftp_user(this)">(<?php print __('delete') ?>)</a>
                                    <input type="hidden" class="v-ftp-user-deleted" name="v_ftp_user[<?php print $i ?>][delete]" value="0" />
                                    <input type="hidden" class="v-ftp-user-is-new" name="v_ftp_user[<?php print $i ?>][is_new]" value="<?php print htmlentities($ftp_user['is_new']) ?>" />
                                </td>
                            </tr>
                            <tr>
                                <td class="vst-text step-left input-label">
                                    <?php print __('Username'); ?><br>
                                    <span style="font-size: 10pt; color:#777;"><?php print __('Prefix will be automaticaly added to username', $user . "_"); ?></span>
                                </td>
                            </tr>
                            <tr>
                                <td class="step-left">
                                    <input type="text" size="20" class="vst-input v-ftp-user" <?php print $ftp_user['is_new'] != 1 ? 'disabled="disabled"' : '' ?> name="v_ftp_user[<?php print $i ?>][v_ftp_user]" value="<?= htmlentities(trim($v_ftp_user, "'")) ?>">
                                    <small class="hint"></small>
                                </td>
                            </tr>
                            <tr>
                                <td class="vst-text step-left  input-label">
                                    <?php print __('Password'); ?> / <a href="javascript:void(0);" onClick="FTPrandom(this)" ; class="generate"><?php print __('generate'); ?></a>
                                </td>
                            </tr>
                            <tr>
                                <td class="step-left">
                                    <input type="text" class="vst-input v-ftp-user-psw password" name="v_ftp_user[<?php print $i ?>][v_ftp_password]" value="<?= htmlentities(trim($v_ftp_password, "'")) ?>">
                                </td>
                            </tr>

                            <tr>
                                <td class="vst-text step-left input-label">
                                    <?php print __('Path'); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="step-left">
                                    <input type="hidden" class="vst-input v-ftp-pre-path" name="v_ftp_pre_path" value="<?php print !empty($v_ftp_pre_path) ? htmlentities(trim($v_ftp_pre_path, "'")) : '/'; ?>">
                                    <input type="text" class="vst-input v-ftp-path" name="v_ftp_user[<?php print $i ?>][v_ftp_path]" value=".htmlentities(trim($v_ftp_path, "'"))?>">
                                                <br /><span class="ftp-path-prefix"><?= htmlentities(trim($v_ftp_pre_path, "'")) ?></span><span class="ftp-path-value v-ftp-path-hint"></span>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td class="vst-text step-left input-label">
                                                 <?php print __('Send FTP credentials to email'); ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="step-left">
                                                <input type="text"  class="vst-input" name="v_ftp_user[<?php print $i ?>][v_ftp_email]" value="<?= htmlentities(trim($v_ftp_email, "'")) ?>">
                                            </td>
                                        </tr>
                                </table>
                                    <?php endforeach; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="vst-text step-top v-add-new-user step-bottom"  style="display: none;">
                                    <a class="additional-control" onClick="App.Actions.WEB.add_ftp_user_form()"><?= __('Add one more FTP Account') ?></a>
                                </td>
                            </tr>
                        </table>
        <button type="submit" class="btn btn-primary btn-block">Confirm</button>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/web" class="btn btn-default btn-block">Back</a>
        <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
        <input type="hidden" name="ok" value="Add">
    </form>
</div>
<?php
// echo "<pre>", print_r($data);
