<div class="col-4">
    <?php if (!empty($_SESSION['error_msg']) || !empty($_SESSION['ok_msg'])) { ?>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
    <?php } ?>
    <form name="v_add_web" action="https://<?= $_SERVER['HTTP_HOST'] ?>/web/add" method="post">
        <label for="v_domain">Domain</label> <span style="color:red">*</span>
        <div class="input-group mb-3">
            <input type="text" name="v_domain" id="v_domain" class="form-control" placeholder="Domain" required>
        </div>
        <label for="v_ip">IP Address</label>
        <div class="input-group mb-3">
            <select name="v_ip" class="form-control">
                <?php foreach ($ips as $ip => $value) { ?>
                    <option value="<?= $value['NAT'] ?>"><?= $value['NAT']  ?></option>
                <?php } ?>

            </select>
        </div>
        <div class="input-group form-control mb-3">
            <input type="checkbox" name="v_dns" id="dns" checked=yes>
            <label class="" for="dns"> &nbsp; DNS Support</label>
        </div>

        <div class="input-group form-control mb-3">
            <input type="checkbox" name="v_mail" id="mail" checked=yes>
            <label for="mail"> &nbsp; Mail Support</label>
        </div>

        <div class="input-group mb-3">
            <b><u><a href="javascript:elementHideShow('advtable');" style="text-decoration: none;color : #000;">Advanced options</a></u></b>
        </div>

        <div style="display:<?php if (empty($v_adv)) echo 'none'; ?> ;" id="advtable">
            <label for="v_aliases">Aliases</label>
            <div class="input-group mb-3">
                <textarea name="v_aliases" class="form-control" value="<?= $v_aliases ?>" row=10 col=3></textarea>
            </div>
            <?php if (!empty($_SESSION['PROXY_SYSTEM'])) { ?>
                <div class="input-group form-control mb-3">
                    <input type="checkbox" name="v_proxy" id="proxy" <?php if (isset($_SESSION['PROXY_SYSTEM'])) echo 'checked=yes' ?>>
                    <label for="proxy"> &nbsp; Proxy Support</label>
                </div>

                <div style="padding-left: 30px;">
                    <label for="v_proxy_ext">Proxy Extensions</label>
                    <div class="input-group mb-3">
                        <textarea name="v_proxy_ext" class="form-control" row=10 col=3>jpg, jpeg, gif, png, ico, svg, css, zip, tgz, gz, rar, bz2, exe, pdf, doc, xls, ppt, txt, odt, ods, odp, odf, tar, bmp, rtf, js, mp3, avi, mpeg, flv, html, htm</textarea>
                    </div>
                </div>
            <?php } ?>
            <div class="input-group form-control mb-3">
                <input type="checkbox" name="v_ssl" id="ssl" onclick="javascript:elementHideShow('ssltable');">
                <label class="" for="ssl"> &nbsp; SSL Support</label>
            </div>

            <div style="display:<?php if (empty($v_ssl)) {
                                    echo 'none';
                                } else {
                                    echo 'block';
                                } ?>;padding-left:30px;" id="ssltable">
                <div class="input-group form-control mb-3">
                    <input type="checkbox" name="v_letsencrypt" id="letsencrypt" <?php if ($v_ssl == "yes") echo "checked"; ?>>
                    <label class="" for="letsencrypt"> &nbsp; Lets Encrypt Support</label>
                </div>
                <div class="vst-text input-label lets-encrypt-note step-left">
                    <?= __('Your certificate will be automatically issued in 5 minutes') ?>
                </div>
                <label for="v_ssl_home"> SSL Home Directory </label>
                <div class="input-group mb-3">
                    <select class="form-control" name="v_ssl_home">
                        <option value='same'> public_html </option>
                        <option value='single'>public_shtml</option>
                    </select>
                </div>
                <label for="v_ssl_crt">SSL Certificate</label>&nbsp; / &nbsp; <a href="/ssl/index/<?= $v_domain ?>" class="generate" target="_blank" ><?php print __('Generate CSR'); ?></a>
                <div class="input-group mb-3">
                    <textarea name="v_ssl_crt" class="form-control" value="<?= htmlentities(trim($v_ssl_crt, "'")) ?>" row=10 col=3></textarea>
                </div>

                <label for="v_ssl_key">SSL Key</label>
                <div class="input-group mb-3">
                    <textarea name="v_ssl_key" class="form-control" value="<?= htmlentities(trim($v_ssl_key, "'")) ?>" row=10 col=3></textarea>
                </div>

                <label for="v_ssl_ca">SSL Certificate Authority/ Intermediate</label> / <em>(Optional)</em>
                <div class="input-group mb-3">
                    <textarea name="v_ssl_ca" class="form-control" value="<?= htmlentities(trim($v_ssl_ca, "'")) ?>" row=10 col=3></textarea>
                </div>
            </div>
            <label for="v_stats"> Web Statistics </label>
            <div class="input-group mb-3">
                <select class="form-control" name="v_stats">
                    <?php foreach ($stats as $stat) { ?>
                        <option value="<? $stat ?>"> <?= $stat ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-group form-control mb-3 stats-auth">
                <input type="checkbox" name="v_stats_auth" id="stats_auth" <?php if (!empty($v_stats_user)) echo "checked=yes" ?> onclick="javascript:elementHideShow('statstable');">
                <label for="stats_auth"> &nbsp; Statistics Authorization</label>
            </div>
            <div style="display:<?php if (empty($v_stats_user)) {
                                    echo 'none';
                                } else {
                                    echo 'block';
                                } ?> ;padding-left:30px;" id="statstable" name="v-add-web-domain-stats-user">
                <label for="v_stats_user">Username</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_stats_user" class="form-control" placeholder="Username" required>
                </div>
                <label for="v_stats_password">Password </label>
                &nbsp; / &nbsp; <a href="javascript:WEBrandom();" class="generate"><?php print __('generate'); ?></a>
                <div class="input-group mb-3">
                    <input type="text" name="v_stats_password" class="form-control" placeholder="Password" data-lpignore="true" required>
                </div>
                <div class="input-group form-control mb-3 stats-auth">
                    <input type="checkbox" name="v_ftp" id="ftp" <?php if (!empty($v_stats_user)) echo "checked=yes" ?> onclick="App.Actions.WEB.toggle_additional_ftp_accounts(this)">
                    <label for="ftp"> &nbsp; Additional FTP Account</label>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Confirm</button>
        <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/web" class="btn btn-default btn-block">Back</a>
        <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
        <input type="hidden" name="ok" value="Add">
    </form>
</div>

<script>
    GLOBAL.FTP_USER_PREFIX = <?= json_encode($user . '_') ?>;
    GLOBAL.FTP_USER_PREPATH = <?= json_encode($v_ftp_user_prepath) ?>;
</script>
<?php
// echo "<pre>", print_r($data);
