<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>
<p class="text-center">
    <?php
    echo $_SESSION['error_msg'];
    $_SESSION['error_msg'] = NULL;
    ?>
</p>
<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add Web Domain
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Domain</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="package" data-filter-control="input" data-sortable="true">IP Address</th>
            <th data-field="disk" data-filter-control="input" data-sortable="true" title="Disk"><i class="fas fa-hdd"></i></th>
            <th data-field="bandwidth" data-filter-control="input" data-sortable="true" title="Bandwidth"><i class="fas fa-exchange-alt"></i></th>
            <th data-field="web" data-filter-control="input" data-sortable="true" title="SSL"><i class="fas fa-lock"></i></i></th>
            <th data-field="mail" data-filter-control="input" data-sortable="true">Statistics</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
                <td> <b><? echo $key ?></b></td>
                <td>
                    <a class="like" href="http://<?= $key ?>">
                        <i class="fas fa-external-link-square-alt status-icon lightblue status-icon dim"></i>
                    </a>&nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/edit/<?php if (isset($_SESSION['look'])) {
                                                                                            echo $_SESSION['look'];
                                                                                        } else {
                                                                                            echo $_SESSION['user'];
                                                                                        } ?>/<?= $key ?>" title="Edit Web Domain">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>&nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/weblog/index/<?= $key ?>/access" title="Access Log">
                        <i class="fas fa-binoculars status-icon purple status-icon dim"></i>
                    </a>&nbsp;
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/weblog/index/<?= $key ?>/error" title="Error Log">
                        <i class="fa fa-exclamation" aria-hidden="true"></i>
                    </a>&nbsp;
                    <?php if ($_SESSION['user'] == 'admin') {

                        if ($each['SUSPENDED'] != 'yes') { ?>
                            <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/suspend/<?php if (isset($_SESSION['look'])) {
                                                                                                        echo $_SESSION['look'];
                                                                                                    } else {
                                                                                                        echo $_SESSION['user'];
                                                                                                    } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>"" title=" Suspend">
                                <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                        <?php } else { ?>
                            <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/unsuspend/<?php if (isset($_SESSION['look'])) {
                                                                                                            echo $_SESSION['look'];
                                                                                                        } else {
                                                                                                            echo $_SESSION['user'];
                                                                                                        } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>"" title=" Unsuspend">
                                <i class="fas fa-play status-icon highlight status-icon dim do_suspend"></i>
                            </a>&nbsp;
                    <?php }
                    } ?>
                    <a class="remove" href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/delete/<?php if (isset($_SESSION['look'])) {
                                                                                                echo $_SESSION['look'];
                                                                                            } else {
                                                                                                echo $_SESSION['user'];
                                                                                            } ?>/<?= $key ?>/<?= $_SESSION['token'] ?>" title="Delete">
                        <i class="fa fa-trash"></i>
                    </a>&nbsp;
                </td>
                <td><? echo $each['IP'] ?></td>
                <td><? echo $each['DISK_QUOTA'] ?> MB</td>
                <td><? echo $each['U_BANDWIDTH'] ?> MB</td>
                <td><? echo $each['SSL'] ?></td>
                <td><? echo $each['STATS'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php
// echo "<pre>", print_r($data, true);
?>