<div class="select" style="display:none">
    <select class="form-control" id="locale">
        <option value="en-US" selected>en-US</option>
    </select>
</div>

<div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
        <i class="fas fa-trash status-icon red status-icon dim do_delete"></i> Delete
    </button>
    <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/add" id="add" class="btn btn-primary">
        <i class="fas fa-plus-circle status-icon"></i> Add Web Domain
    </a>
</div>

<table id="table" data-toggle="table" data-toolbar="#toolbar" data-search="true" data-show-refresh="true" data-show-toggle="false" data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true" data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true" data-id-field="name" data-page-list="[10, 25, 50, 100, all]" data-show-footer="false" data-response-handler="responseHandler">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="name" data-filter-control="input" data-sortable="true">Domain</th>
            <th data-field="action" data-filter-control="input" data-sortable="true">Action</th>
            <th data-field="package" data-filter-control="input" data-sortable="true">IP Address</th>
            <th data-field="disk" data-filter-control="input" data-sortable="true" title="Disk"><i class="fas fa-hdd"></i></th>
            <th data-field="bandwidth" data-filter-control="input" data-sortable="true" title="Bandwidth"><i class="fas fa-exchange-alt"></i></th>
            <th data-field="web" data-filter-control="input" data-sortable="true" title="SSL"><i class="fas fa-lock"></i></i></th>
            <th data-field="mail" data-filter-control="input" data-sortable="true">Statistics</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $each) {
        ?>
            <tr>
                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
                <td> <b><? echo $key ?></b></td>
                <td>
                    <a class="like" href="http://<?= $key ?>">
                        <i class="fas fa-external-link-square-alt status-icon lightblue status-icon dim"></i>
                    </a>
                    <a class="like" href="https://<?= $_SERVER['HTTP_HOST'] ?>/web/edit" title="Edit Web Domain">
                        <i class="fas fa-pencil-alt status-icon orange status-icon dim"></i>
                    </a>
                    <a class="like" href="" title="Access Log">
                        <i class="fas fa-binoculars status-icon purple status-icon dim"></i>
                    </a>
                    <a class="like" href="" title="Suspend">
                        <i class="fas fa-pause status-icon highlight status-icon dim do_suspend"></i>
                    </a>
                    <a class="remove" href="" title="Delete">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
                <td><? echo $each['IP'] ?></td>
                <td><? echo $each['DISK_QUOTA'] ?> MB</td>
                <td><? echo $each['U_BANDWIDTH'] ?> MB</td>
                <td><? echo $each['SSL'] ?></td>
                <td><? echo $each['STATS'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

</div>

<?php
//echo "<pre>", print_r($data, true);
?>