<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <?
    echo "<pre>", print_r($data, true), "</pre>";
    ?>

    <title>Add User</title>

    <div class="col-10">
        <p class="login-box-msg"><b>Editing CronJob</b></p>
        <p class="text-center">
            <?php
            echo $_SESSION['error_msg'], "<br>", $_SESSION['ok_msg'];
            $_SESSION['error_msg'] = NULL;
            $_SESSION['ok_msg'] = NULL;
            ?>
        </p>
        <form name="v_add_user" action="https://<?= $_SERVER['HTTP_HOST'] ?>/cron/edit/<?php if (isset($_SESSION['look'])) {
                                                                                            echo $_SESSION['look'];
                                                                                        } else {
                                                                                            echo $_SESSION['user'];
                                                                                        } ?>/<?= $job_id ?>/<?= $_SESSION['token'] ?>" method="post">
            <label for="v_cmd">Command</label>
            <div class="input-group mb-3">
                <input type="text" name="v_cmd" class="form-control" placeholder="Command" value="<?= $v_cmd ?>">
            </div>

            <table style="width: 200px;">
                <label for="v_min">Minutes</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_min" class="form-control" placeholder="Minutes" value="<?= $v_min ?>">
                </div>
                <label for="v_hour">Hour</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_hour" class="form-control" placeholder="Hour" value="<?= $v_hour ?>">
                </div>
                <label for="v_day">Day</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_day" class="form-control" placeholder="Day" value="<?= $v_day ?>">
                </div>
                <label for="v_month">Month</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_month" class="form-control" placeholder="Month" value="<?= $v_month ?>">
                </div>
                <label for="v_wday">Day of week</label>
                <div class="input-group mb-3">
                    <input type="text" name="v_wday" class="form-control" placeholder="Day of week" value="<?= $v_wday ?>">
                </div>
            </table>

            <div class="row">
                <!-- /.col -->

                <!-- /.col -->
            </div>

            <button type="submit" class="btn btn-primary btn-block">Confirm</button>

            <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reset" class="btn btn-default btn-block">Back</a>

            <input type="hidden" name="token" value="<?php echo $_SESSION['token']; ?>">
            <input type="hidden" name="save" value="save">

        </form>
    </div>

</body>


</html>

<?php
echo "<pre>", print_r($data);
